# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# Print installed Cline version.
set -euo pipefail
CLINE_BIN="${CLINE_BIN:-$(command -v cline 2>/dev/null || true)}"
if [[ -z "$CLINE_BIN" || ! -x "$CLINE_BIN" ]]; then
  echo "cline not found" >&2
  exit 1
fi
"$CLINE_BIN" --version
