# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# Print the directory Cline scans for skills.
set -euo pipefail
CLINE_DATA_DIR="${CLINE_DATA_DIR:-$HOME/.cline}"
echo "CLINE_DATA_DIR=$CLINE_DATA_DIR"
echo "SKILLS_DIR=$CLINE_DATA_DIR/skills"
echo "---"
echo "Each skill is a directory containing SKILL.md with"
echo "YAML frontmatter. Required fields vary by Cline version."
