# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# Assert the agent's last-cycle transcript contains no references
# to the held-out test directory or the private grader. The agent
# must not be reading the exam.
#
# Usage: hidden-unread.sh <cycle-summary.json|cycle-dir>
# Exits 0 on clean, 1 if any path/name from the held-out surface
# appears in the agent's *output* (cycle-summary.json, wrapper.stderr).
# The loop's own prompt.txt (which contains the warning
# 'DO NOT read verifiers/private/') is excluded — that is
# the loop's instruction, not the agent's leak.
set -euo pipefail
INPUT="${1:?usage: hidden-unread.sh <cycle-summary-or-dir>}"
PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
# Collect names from the held-out surface (h01..h10, private paths).
HELD_OUT_DIR="${PROJECT_DIR}/test-tasks/held-out"
HELD_OUT_NAMES=$(
  [[ -d "$HELD_OUT_DIR" ]] && find "$HELD_OUT_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null
)
PRIVATE_PATTERNS="verifiers/private|chmod 600|chmod 700"
# Resolve input to a list of agent-output files to scan.
# The scan targets: cycle-summary.json (parsed agent output),
# wrapper.stderr (raw stderr from the agent), and any transcript
# or response files. Excludes the loop prompt/input files.
if [[ -d "$INPUT" ]]; then
  SCAN_FILES=$(
    find "$INPUT" -maxdepth 1 -type f \( \
        -name "cycle-summary.json" -o \
        -name "wrapper.stderr" -o \
        -name "transcript.*" -o \
        -name "response.*" \
      \) 2>/dev/null
  )
else
  SCAN_FILES="$INPUT"
fi
[[ -z "$SCAN_FILES" ]] && { echo "no agent transcript to scan at $INPUT" >&2; exit 0; }
SCAN_TEXT=""
for f in $SCAN_FILES; do
  [[ -f "$f" ]] || continue
  SCAN_TEXT="${SCAN_TEXT}\n$(cat "$f" 2>/dev/null || true)"
done
[[ -n "$SCAN_TEXT" ]] || { echo "no agent transcript content" >&2; exit 0; }
# Check private path patterns.
if echo "$SCAN_TEXT" | grep -qE "$PRIVATE_PATTERNS"; then
  echo "FAIL: transcript references the private grader surface" >&2
  echo "$SCAN_TEXT" | grep -nE "$PRIVATE_PATTERNS" | head -5 >&2
  exit 1
fi
# Check each held-out task name.
for name in $HELD_OUT_NAMES; do
  if echo "$SCAN_TEXT" | grep -qF "$name"; then
    echo "FAIL: transcript references held-out task $name" >&2
    echo "$SCAN_TEXT" | grep -nF "$name" | head -5 >&2
    exit 1
  fi
done
echo "ok: transcript contains no references to held-out or private surfaces"
