# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# Assert the agent's last-cycle transcript contains no references
# to the held-out test directory or the private grader. The agent
# must not be reading the exam.
#
# Usage: hidden-unread.sh <file> [<file>...]
# Exits 0 if none of the supplied agent-output files contain a
# reference to the held-out surface (h01..hNN) or to the private
# grader paths. Exits 1 on any leak.
#
# The loop (cycle.sh) passes only the files the agent produced
# (wrapper.stderr, transcript.txt, .iterations/<cycle>/*). It does
# NOT pass cycle-summary.json, input.json, or prompt.txt, which
# are the loop's own writes (they echo the loop's prompt and
# would trigger false positives on the verifiers/private rule).
set -euo pipefail
PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
# Collect names from the held-out surface (h01..h10, private paths).
HELD_OUT_DIR="${PROJECT_DIR}/test-tasks/held-out"
HELD_OUT_NAMES=$(
  [[ -d "$HELD_OUT_DIR" ]] && find "$HELD_OUT_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null
)
PRIVATE_PATTERNS="verifiers/private|chmod 600|chmod 700"
# Accept one or more files as args. Each is an agent-output file
# (NOT the loop's own writes like cycle-summary.json, which echoes
# the loop's prompt and would trigger false positives).
[[ $# -lt 1 ]] && { echo "usage: hidden-unread.sh <file> [<file>...]" >&2; exit 2; }
SCAN_FILES=("$@")
SCAN_TEXT="
"
for f in "${SCAN_FILES[@]}"; do
  [[ -f "$f" ]] || continue
  SCAN_TEXT="${SCAN_TEXT}$(cat "$f" 2>/dev/null || true)
"
done
[[ -n "$SCAN_TEXT" && "$SCAN_TEXT" != $
 ]] || { echo "no agent transcript content" >&2; exit 0; }
# Check private path patterns.
if echo "$SCAN_TEXT" | grep -qE "$PRIVATE_PATTERNS"; then
  echo "FAIL: transcript references the private grader surface" >&2
  echo "$SCAN_TEXT" | grep -nE "$PRIVATE_PATTERNS" | head -5 >&2
  exit 1
fi
# Check each held-out task name.
for name in $HELD_OUT_NAMES; do
  if echo "$SCAN_TEXT" | grep -qF "$name"; then
    echo "FAIL: transcript references held-out task $name" >&2
    echo "$SCAN_TEXT" | grep -nF "$name" | head -5 >&2
    exit 1
  fi
done
echo "ok: transcript contains no references to held-out or private surfaces"
