# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# Print seconds spent in the most recent cycle. Records the
# wall-clock per cycle so the loop can reward fast-improving
# cycles and penalize slow ones (the smallness / speed signal).
#
# Usage: per-cycle-wall-clock.sh [--record SECONDS] | (no flag = read latest)
set -euo pipefail
PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
STATE_DIR="${PROJECT_DIR}/logs"
CLOCK_FILE="${STATE_DIR}/.per-cycle-wall-clock.tsv"
if [[ "${1:-}" == "--record" ]]; then
  SEC="${2:?usage: per-cycle-wall-clock.sh --record SECONDS [CYCLE]}"
  CYCLE="${3:-$(date +%s)}"
  mkdir -p "$STATE_DIR"
  echo -e "${CYCLE}\t${SEC}" >> "$CLOCK_FILE"
  echo "recorded: cycle=$CYCLE sec=$SEC"
  exit 0
fi
[[ -s "$CLOCK_FILE" ]] || { echo 0; exit 0; }
tail -1 "$CLOCK_FILE" | awk -F"\t" "{print \$2}"
