# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# verifiers/instruments/smallness.sh - code-quality
# Soft reward: penalizes candidates that exceed the LOC budget.
# Parses MAX_LOC_PER_CYCLE from GOAL.md (default 200).
#
# Score: 1.0 if LOC <= budget, linear decay to 0.5 at 2x budget, 0.0 above.
# This is a real (non-stub) measurement. No HITL required.
#
# What it counts: lines in skills/<artifact>/ and test-tasks/.
#
# Usage: smallness.sh
#   Prints a float in [0.0, 1.0].
set -euo pipefail
PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
BUDGET=$(python3 - "$PROJECT_DIR/GOAL.md" 2>/dev/null <<'PY'
import re, sys
try:
    text = open(sys.argv[1]).read()
    m = re.search(r'MAX_LOC_PER_CYCLE[ \t]*=[ \t]*([0-9]+)', text)
    print(m.group(1) if m else '200')
except Exception:
    print('200')
PY
)

LOC=0
for d in "$PROJECT_DIR/skills" "$PROJECT_DIR/test-tasks"; do
  [[ -d "$d" ]] || continue
  while IFS= read -r f; do
    [[ -f "$f" ]] && LOC=$((LOC + $(wc -l < "$f" 2>/dev/null || echo 0)))
  done < <(find "$d" -type f 2>/dev/null)
done

python3 - "$BUDGET" "$LOC" <<'PY'
import sys
budget = int(sys.argv[1])
loc = int(sys.argv[2])
if loc <= budget:
    print(1.0)
elif loc <= 2 * budget:
    print(round(1.0 - 0.5 * (loc - budget) / budget, 4))
else:
    print(0.0)
PY
