# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# Assert the visible test set has not been modified since the
# last cycle. The agent must not be able to change a test to
# pass it. Stores the SHA-256 of the design set on first run,
# compares on subsequent runs.
#
# Usage: test-freshness.sh [--record]
#   (no flag): compare current SHA to recorded; exit 1 if changed.
#   --record:  record the current SHA as the baseline.
set -euo pipefail
PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
STATE_DIR="${PROJECT_DIR}/logs"
FRESHNESS_FILE="${STATE_DIR}/.test-freshness.sha256"
TASK_ROOT="${PROJECT_DIR}/test-tasks/design"
[[ -d "$TASK_ROOT" ]] || { echo "no design set at $TASK_ROOT" >&2; exit 1; }
CURRENT=$(find "$TASK_ROOT" -type f -name "grade.sh" -o -name "prompt.txt" \
             -o -name "README.md" 2>/dev/null | sort \
             | xargs -I {} shasum -a 256 {} 2>/dev/null \
             | shasum -a 256 | awk "{print \$1}")
if [[ "${1:-}" == "--record" ]]; then
  mkdir -p "$STATE_DIR"
  echo "$CURRENT" > "$FRESHNESS_FILE"
  echo "recorded: $CURRENT"
  exit 0
fi
if [[ ! -s "$FRESHNESS_FILE" ]]; then
  echo "no baseline recorded; pass-through (first cycle)" >&2
  exit 0
fi
PRIOR=$(cat "$FRESHNESS_FILE")
if [[ "$PRIOR" != "$CURRENT" ]]; then
  echo "FAIL: design set modified since last cycle" >&2
  echo "  prior:    $PRIOR" >&2
  echo "  current:  $CURRENT" >&2
  exit 1
fi
echo "ok: design set unchanged ($CURRENT)"
