# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# verifiers/instruments/unit-tests.sh - tests
# Unit test pass rate on the candidate. 1.0 = all pass, 0.0 = all fail.
#
# Tool hint: pytest, go test, jest, vitest, cargo test, etc.
#
# This is a stub. The default returns 0.0. Wire your
# real tool invocation in the section marked HITL below.
#
# Output: float in [0.0, 1.0]
# Exit code: 0 on measurement present, non-zero on tool error.
#
# Usage: unit-tests.sh
set -euo pipefail
PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"

# ----- HITL: wire your tool here -----
# Replace the next 3-5 lines with the real tool invocation.
# The variable MEASUREMENT should be a number in [0.0, 1.0]
# (1.0 = pass, 0.0 = fail, anything in between is partial credit).
# Exit non-zero ONLY on tool error (not on constraint violation).
MEASUREMENT=0.0

# ----- end HITL -----

echo "$MEASUREMENT"
