#!/usr/bin/env python3
"""harness-scaffold — scaffold a loss-function harness tree.

Reads a /goal prompt, extracts the structured sections, and
writes the matching project tree at the project root. See
SKILL.md for the contract.

Usage:
  harness-scaffold --project-root PATH [--goal-prompt PATH] \
                   [--runtime {cline|codex|aider}] [--no-private]
"""
from __future__ import annotations

import argparse
import os
import re
import stat
import sys
from pathlib import Path
from textwrap import dedent

GENERATED_HEADER = (
    "# auto-generated by harness-scaffold v1.0\n"
    "# DO NOT EDIT — re-run `harness-scaffold` to regenerate\n"
    "# (this header marker is how the scaffold detects safe-to-overwrite files)\n"
)

AGENT_EDITED_MARKER = "# agent-edited: yes"


def is_user_edited(path):
    if not path.exists():
        return False
    try:
        with path.open() as f:
            head = "".join(f.readline() for _ in range(5))
    except Exception:
        return False
    return AGENT_EDITED_MARKER in head


def safe_write(path, content, executable=False):
    if is_user_edited(path):
        print("  skip (user-edited): " + str(path), file=sys.stderr)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        f.write(content)
    if executable:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print("  write: " + str(path), file=sys.stderr)


def chmod_700(path):
    if path.exists():
        path.chmod(0o700)


def chmod_600(path):
    if path.exists():
        path.chmod(0o600)


def extract_design_tasks(prompt):
    m = re.search(r"Design-set tasks.*?\n\n(.*?)(?=\n\n#|\Z)", prompt, re.S)
    if not m:
        return []
    block = m.group(1)
    tasks = []
    for line in block.splitlines():
        line = line.strip()
        m2 = re.match(r"^\d+\.\s+(.+)$", line)
        if not m2:
            continue
        desc = m2.group(1).strip()
        if "`" in desc:
            em = max(desc.rfind(" — "), desc.rfind(" - "))
            if em > 0:
                desc = desc[em + 3:].strip()
            else:
                m3 = re.match(r"^`[^`]+`\s*(.*)$", desc)
                if m3:
                    desc = m3.group(1).strip()
        desc = desc.strip("`'\"")
        tasks.append(desc)
    return tasks


def extract_held_out_tasks(prompt):
    m = re.search(r"Held-out tasks.*?\n\n(.*?)(?=\n\n#|\Z)", prompt, re.S)
    if not m:
        return [f"h{i:02d}" for i in range(1, 11)]
    block = m.group(1)
    range_match = re.search(
        r"(h\d{2})[^a-zA-Z0-9]{1,8}(?:…|\.{2,}|—|–|through|to| - )[^a-zA-Z0-9]{1,8}(h\d{2})",
        block, re.I,
    )
    if range_match:
        try:
            a = int(range_match.group(1)[1:])
            b = int(range_match.group(2)[1:])
            if a > b:
                a, b = b, a
            return [f"h{n:02d}" for n in range(a, b + 1)]
        except Exception:
            pass
    explicit = re.findall(r"\b(h\d{2})\b", block)
    if explicit:
        seen = set()
        out = []
        for h in explicit:
            if h not in seen:
                seen.add(h)
                out.append(h)
        return out
    return [f"h{i:02d}" for i in range(1, 11)]


def extract_runtime(prompt):
    m = re.search(r"inner loop is the `(\w+)` CLI", prompt)
    return m.group(1) if m else "cline"


def slugify(s):
    s = s.lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip("-")


def word_truncate(s, max_len):
    """Truncate at word boundary, max max_len chars."""
    if len(s) <= max_len:
        return s
    truncated = s[:max_len]
    # Find last hyphen
    last_hyphen = truncated.rfind("-")
    if last_hyphen > max_len // 2:
        return truncated[:last_hyphen]
    return truncated


INTEGRITY_SH = (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# verifiers/integrity.sh — anti-cheat guards. Runs BEFORE every\n"
    + "# design-set cycle. Exits 0 if the harness is intact, non-zero\n"
    + "# if any guard fires.\n"
    + "#\n"
    + "# Default guards cover the 5 cheats from BUILDING-A-GREAT-HARNESS.md\n"
    + "# V0-7: test deletion, stub-always-passes, sleep-to-pass, rules-file\n"
    + "# modification, hidden-dir read. Replace with project-specific guards\n"
    + "# before the /goal prompt is emitted.\n"
    + "#\n"
    + "# Usage: integrity.sh [--help] [--project-root PATH]\n"
    + "#   (no flag):  report. exit 0 if all guards pass, 1 if any fail.\n"
    + "#   --project-root PATH: override the auto-detected project root.\n"
    + "#   --help:     show this help and exit 0.\n"
    + "#\n"
    + "# Project root is auto-detected from this script's location\n"
    + "# (../.. from verifiers/integrity.sh). The $PROJECT_DIR env var\n"
    + "# overrides it; --project-root overrides the env var.\n"
    + "\n"
    + "set -euo pipefail\n"
    + "\n"
    + 'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
    + 'DEFAULT_PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"\n'
    + 'PROJECT_DIR="${PROJECT_DIR:-$DEFAULT_PROJECT_ROOT}"\n'
    + "\n"
    + "while [[ $# -gt 0 ]]; do\n"
    + '  case "$1" in\n'
    + '    --help|-h)\n'
    + '      sed -n "2,/^[^#]/{/^[^#]/q; p}" "$0" | sed "s/^# \\{0,1\\}//"\n'
    + "      exit 0\n"
    + "      ;;\n"
    + '    --project-root) PROJECT_DIR="$2"; shift 2 ;;\n'
    + '    *) echo "unknown flag: $1" >&2; exit 2 ;;\n'
    + "  esac\n"
    + "done\n"
    + "\n"
    + "[[ -d \"$PROJECT_DIR\" ]] || { echo \"integrity: project root not found: $PROJECT_DIR\" >&2; exit 2; }\n"
    + "\n"
    + "FAILS=0\n"
    + "REPORT=\"\"\n"
    + "\n"
    + "check() {\n"
    + '  local name="$1"; shift\n'
    + '  if "$@"; then\n'
    + '    REPORT+="ok    ${name}\n"\n'
    + "  else\n"
    + '    REPORT+="FAIL  ${name}\n"\n'
    + "    FAILS=$((FAILS + 1))\n"
    + "  fi\n"
    + "}\n"
    + "\n"
    + "# ----- guards (project-specific) -----\n"
    + "\n"
    + "guard_no_grade_todo_stub() {\n"
    + '  local d="$PROJECT_DIR/test-tasks/design"\n'
    + '  [[ -d "$d" ]] || return 0\n'
    + '  local g\n'
    + '  while IFS= read -r g; do\n'
    + '    if grep -qE "TODO.*grade|TODO.*meta-fill" "$g" 2>/dev/null; then\n'
    + "      return 1\n"
    + "    fi\n"
    + "  done < <(find \"$d\" -name grade.sh 2>/dev/null)\n"
    + "  return 0\n"
    + "}\n"
    + "\n"
    + "guard_no_stub_always_pass() {\n"
    + '  local d="$PROJECT_DIR/test-tasks/design"\n'
    + '  [[ -d "$d" ]] || return 0\n'
    + '  local g\n'
    + '  while IFS= read -r g; do\n'
    + '    if ! grep -qE "(\\btest\\b|\\bassert\\b|\\bgrep\\b|\\bdiff\\b|\\bjq\\b|\\bpytest\\b|\\bgo test\\b|\\bnode -e\\b|\\bbash -c\\b|\\bpython3? -c\\b|\\bpython3? -)" "$g" 2>/dev/null; then\n'
    + "      return 1\n"
    + "    fi\n"
    + "  done < <(find \"$d\" -name grade.sh 2>/dev/null)\n"
    + "  return 0\n"
    + "}\n"
    + "\n"
    + "guard_no_sleep_in_grader() {\n"
    + '  local d="$PROJECT_DIR/test-tasks/design"\n'
    + '  [[ -d "$d" ]] || return 0\n'
    + '  local g\n'
    + '  while IFS= read -r g; do\n'
    + '    if grep -qE "time\\.Sleep|\\bsleep [0-9]" "$g" 2>/dev/null; then\n'
    + "      return 1\n"
    + "    fi\n"
    + "  done < <(find \"$d\" -name grade.sh 2>/dev/null)\n"
    + "  return 0\n"
    + "}\n"
    + "\n"
    + "guard_agents_md_has_hard_rules() {\n"
    + '  local f="$PROJECT_DIR/AGENTS.md"\n'
    + '  [[ -f "$f" ]] || return 1\n'
    + '  grep -q "DO NOT read .*verifiers/private" "$f" \\\n'
    + '    && grep -q "DO NOT read .*test-tasks/held-out" "$f"\n'
    + "}\n"
    + "\n"
    + "\n"
    + 'printf "%s" "$REPORT"\n'
    + 'if [[ "$FAILS" -gt 0 ]]; then\n'
    + '  echo "" >&2\n'
    + '  echo "integrity: $FAILS guard(s) failed" >&2\n'
    + "  exit 1\n"
    + "fi\n"
    + 'echo "integrity: all guards pass"\n'
    + "exit 0\n"
)


# ----- file content templates -----

AGENTS_MD = lambda project_name: (
    GENERATED_HEADER
    + "\n"
    + "# AGENTS.md - loop driver rules for " + project_name + "\n"
    + "\n"
    + "# This is a V0->V1 production harness. Every section below is a\n"
    + "# stub for the human to fill in. The harness is fully wired and\n"
    + "# will run with the default values; production-quality work\n"
    + "# requires the human to read each HITL section and customize.\n"
    + "\n"
    + "## Hard rules (these NEVER change)\n"
    + "\n"
    + "1. DO NOT read `verifiers/private/` or `test-tasks/held-out/`.\n"
    + "2. DO NOT modify `verifiers/private/` or `test-tasks/held-out/` (held-out target).\n"
    + "3. The only agent invocation is via `verifiers/<runtime>-wrapper.sh`.\n"
    + "4. Before every cycle, run `verifiers/integrity.sh`. If any guard\n"
    + "   fails, refuse to score that cycle.\n"
    + "5. Before every cycle, run `verifiers/instruments/test-freshness.sh`.\n"
    + "   If the design-set SHA has changed, the agent edited a test - refuse.\n"
    + "6. Before every cycle, run `verifiers/instruments/hidden-unread.sh` on\n"
    + "   the agent's last-cycle transcript. If it references held-out or\n"
    + "   private, the held-out score is void.\n"
    + "7. After EACH design-set run, append a one-line entry to\n"
    + "   `logs/iteration-log.md` with cycle number, hypothesis, expected\n"
    + "   failure, pass_rate, weighted_sum, gates, axes_met, wall_clock_s.\n"
    + "8. If weighted_sum doesn't improve by >= 0.05, force entropy: pick\n"
    + "   the OPPOSITE of your last change and apply it. Document it.\n"
    + "9. DO NOT load the `meta-loss-function-development` skill.\n"
    + "   Allowed skills: `loss-function-design`, `harness-engineering`,\n"
    + "   `<runtime>-orchestration`, and the contents of `GOAL.md`.\n"
    + "\n"
    + "## Surface rules (what the agent can read/write) - HITL\n"
    + "\n"
    + "# The default surface is: read $PROJECT_DIR, invoke the wrapper,\n"
    + "# read/write skills/<artifact-name>/, read verifiers/ and\n"
    + "# verifiers/instruments/, append to logs/. The agent must NOT\n"
    + "# read verifiers/private/ or test-tasks/held-out/.\n"
    + "#\n"
    + "# HITL: Customize the surface for your project. For example:\n"
    + "#   - If your project has a `lib/` directory the agent can edit,\n"
    + "#     add it to the read/write list.\n"
    + "#   - If there are files the agent should NEVER touch (e.g.,\n"
    + "#     generated code, vendored deps), list them under DENY.\n"
    + "#\n"
    + "## Workflow (per cycle)\n"
    + "\n"
    + "1. Read `GOAL.md`, this file, `README.md`,\n"
    + "   `verifiers/<runtime>-wrapper.sh`, `verifiers/run-design-set.sh`,\n"
    + "   `verifiers/integrity.sh`, and every script in\n"
    + "   `verifiers/instruments/`.\n"
    + "2. Read each design task's `prompt.txt` and starting file.\n"
    + "3. Run `verifiers/integrity.sh`. If it exits non-zero, STOP and report.\n"
    + "4. Establish baseline: with no candidate skill installed, run\n"
    + "   `PROJECT_DIR=$(pwd) ./verifiers/run-design-set.sh` and record.\n"
    + "5. Begin cycle 1. Write a candidate `skills/<artifact-name>/SKILL.md`\n"
    + "   (and references if needed).\n"
    + "6. Install the skill where the agent picks it up.\n"
    + "7. Run the design set, then run integrity + test-freshness + hidden-unread.\n"
    + "8. Compute multi-axis `axes_met`. If axes_met is true, save\n"
    + "   `logs/best-cycle.json`. If not, force entropy.\n"
    + "9. Iterate. Stop when one of the stop conditions in `GOAL.md` is met.\n"
    + "10. On stop, leave the skill, references, `logs/iteration-log.md`,\n"
    + "    `logs/best-cycle.json`, and `logs/held-out-score.json`.\n"
    + "\n"
    + "## Anti-cheat firewall (HITL: review and extend)\n"
    + "\n"
    + "# The default anti-cheat guards in verifiers/integrity.sh are:\n"
    + "#  1. no-grade-todo-stub         - no grade.sh is a TODO\n"
    + "#  2. no-stub-always-pass        - no grade.sh is empty\n"
    + "#  3. no-sleep-in-grader         - no time.Sleep to mask timing\n"
    + "#  4. agents-md-has-hard-rules   - AGENTS.md still has the rules\n"
    + "#\n"
    + "# HITL: Add project-specific guards to verifiers/integrity.sh.\n"
    + "# Examples: 'no test-file deletion', 'no mock-stubs in test/'.\n"
    + "\n"
    + "## Forced entropy (the loop's meta-policy)\n"
    + "\n"
    + "Each cycle continues from the previous run's entire context.\n"
    + "Local maxima is the default state. Three rules apply:\n"
    + "\n"
    + "1. **Overfit reflection.** Before each cycle, append to\n"
    + "   `logs/iteration-log.md`:\n"
    + "     cycle N: hypothesis=\"<one line>\", expected_failure=\"<one line>\",\n"
    + "     generalizing_or_memorizing=<g|m>, pass_rate=<float>,\n"
    + "     weighted_sum=<float>, axes_met=<bool>, wall_clock_s=<int>\n"
    + "   If memorizing, the next change must REMOVE an eval-shaped\n"
    + "   artifact, not add one.\n"
    + "\n"
    + "2. **Stall entropy.** If weighted_sum did not improve by >= 0.05\n"
    + "   vs prior cycle, pick the OPPOSITE of your last change. Apply it.\n"
    + "   Log it. The OPPOSITE is determined by the agent, not the driver.\n"
    + "\n"
    + "3. **Iteration log is required.** No credit for luck.\n"
    + "\n"
    + "## What this harness scores (multi-axis, all must hold)\n"
    + "\n"
    + "# The default axes are parsed from `GOAL.md`'s Target section.\n"
    + "# Common axes (any subset may apply to your project):\n"
    + "#\n"
    + "#   - pass_rate        (Correctness - design + held-out)\n"
    + "#   - weighted_sum     (Composite of all sub-losses)\n"
    + "#   - integrity        (verifiers/integrity.sh exits 0)\n"
    + "#   - test_freshness   (no AI-modified test files)\n"
    + "#   - hidden_unread    (no held-out or private reads)\n"
    + "#   - smallness        (candidate LOC under MAX_LOC_PER_CYCLE)\n"
    + "#   - linter, type_check, unit_tests, integration_tests,\n"
    + "#     test_coverage, mutation_tests, e2e_tests, regression_tests,\n"
    + "#     contract_tests (test axis)\n"
    + "#   - secret_scan, sast, dependency_audit, sbom (security axis)\n"
    + "#   - a11y, i18n, docs_coverage (UX axis)\n"
    + "#   - observability, trace_coverage (observability axis)\n"
    + "#   - perf_budget, bundle_size, startup_time (performance axis)\n"
    + "#   - hermeticity, determinism, flakiness (reliability axis)\n"
    + "#   - license_audit, supply_chain (compliance axis)\n"
    + "#\n"
    + "# Each axis is a separate instrument in verifiers/instruments/.\n"
    + "# The multi-axis stop condition (in GOAL.md) requires all\n"
    + "# configured axes to hold simultaneously for SUCCESS_AFTER cycles.\n"
    + "\n"
    + "## Per-instrument sub-loss contract (HITL)\n"
    + "\n"
    + "# Each instrument script in verifiers/instruments/:\n"
    + "#   - exits 0 on measurement present, non-zero on tool error\n"
    + "#   - prints a float in [0.0, 1.0] to stdout (1.0 = pass)\n"
    + "#   - has HITL: a 3-5 line section where you wire the real tool\n"
    + "#     invocation (the script ships with a stub that returns 0.0)\n"
    + "#   - is callable from any cwd via PROJECT_DIR=<project-root> <script>\n"
    + "#\n"
    + "# HITL: Wire the instruments that apply to your project. The\n"
    + "# remaining ones stay as 0.0 stubs and the multi-axis stop\n"
    + "# condition ignores axes that aren't in GOAL.md.\n"
)

README_MD = lambda project_name, goal_summary: (
    GENERATED_HEADER
    + "\n"
    + "# " + project_name + "\n"
    + "\n"
    + "Loss-function-driven development project. Scaffolded by\n"
    + "`harness-scaffold` v1.0.\n"
    + "\n"
    + "This is a V0->V1 production harness. The scaffold emits a\n"
    + "fully-wired harness with 33+ instruments, multi-axis scoring,\n"
    + "anti-cheat guards, and HITL-stubs for every project-specific\n"
    + "value. See `GOAL.md` for the contract and `verifiers/integrity.sh`\n"
    + "for the anti-cheat firewall.\n"
    + "\n"
    + "## Quick start\n"
    + "\n"
    + "```bash\n"
    + "# 0. Fill in HITL sections in:\n"
    + "#    - GOAL.md (Target axes, Constraints, Done When)\n"
    + "#    - AGENTS.md (Surface rules, Anti-cheat guards)\n"
    + "#    - verifiers/integrity.sh (add project-specific guards)\n"
    + "#    - verifiers/instruments/*.sh (wire each instrument's HITL section)\n"
    + "\n"
    + "# 1. Establish baseline (no candidate skill installed yet)\n"
    + "PROJECT_DIR=$(pwd) ./verifiers/run-design-set.sh\n"
    + "cat logs/design-set-score.json\n"
    + "\n"
    + "# 2. Verify the anti-cheat firewall is intact\n"
    + "./verifiers/integrity.sh\n"
    + "\n"
    + "# 3. Read AGENTS.md and follow the workflow there\n"
    + "cat AGENTS.md\n"
    + "```\n"
    + "\n"
    + "## Layout\n"
    + "\n"
    + "- `GOAL.md` - the /goal prompt, with multi-axis Target + DONE WHEN\n"
    + "- `AGENTS.md` - loop driver rules (HITL: surface, anti-cheat)\n"
    + "- `verifiers/integrity.sh` - 4 default anti-cheat guards (HITL: extend)\n"
    + "- `verifiers/instruments/*.sh` - 33 instruments (HITL: wire each)\n"
    + "  - Real (non-stub): time-remaining, tokens-remaining,\n"
    + "    tokens-this-iter, cline-version, cline-skills-dir,\n"
    + "    sub-loss-readout, test-freshness, hidden-unread,\n"
    + "    per-cycle-wall-clock, smallness\n"
    + "  - Stubs (return 0.0, HITL to wire): linter, type-check, complexity,\n"
    + "    unit-tests, integration-tests, test-coverage, mutation-tests,\n"
    + "    e2e-tests, regression-tests, contract-tests, secret-scan,\n"
    + "    sast, dependency-audit, sbom, a11y, i18n, docs-coverage,\n"
    + "    observability, trace-coverage, perf-budget, bundle-size,\n"
    + "    startup-time, hermeticity, determinism, flakiness,\n"
    + "    license-audit, supply-chain\n"
    + "- `verifiers/compute_sub_losses.py` - the per-cycle sub-loss scorer\n"
    + "- `verifiers/parse_cline_output.py` - the wrapper output parser\n"
    + "- `verifiers/run-design-set.sh` - runs the design set\n"
    + "- `verifiers/<runtime>-wrapper.sh` - the agent wrapper (HITL: customize)\n"
    + "- `verifiers/private/grader.sh` - HELD-OUT grader (off-limits to agent)\n"
    + "- `test-tasks/design/NN-<name>/` - design tasks (5-10, in 8 categories)\n"
    + "  - Categories: happy-path, error/edge-case, cross-cutting,\n"
    + "    negative, auth/permissions, performance, accessibility, i18n\n"
    + "- `test-tasks/held-out/hNN/` - held-out tasks (5-10, off-limits)\n"
    + "- `skills/<artifact-name>/` - the agent's candidate skill\n"
    + "- `logs/` - the loop's running trace\n"
    + "\n"
    + "## Multi-axis target (read this first)\n"
    + "\n"
    + "`GOAL.md` defines a **multi-axis** target. The loop succeeds when\n"
    + "ALL configured axes hold simultaneously for SUCCESS_AFTER\n"
    + "consecutive cycles. The default axes are:\n"
    + "\n"
    + "| Axis | Source | Default threshold |\n"
    + "|---|---|---|\n"
    + "| pass_rate | design set + held-out | >= 0.8 |\n"
    + "| weighted_sum | composite of all sub-losses | >= 0.85 |\n"
    + "| integrity | verifiers/integrity.sh | exits 0 |\n"
    + "| test_freshness | verifiers/instruments/test-freshness.sh | no SHA change |\n"
    + "| hidden_unread | verifiers/instruments/hidden-unread.sh | no leak |\n"
    + "| smallness | verifiers/instruments/smallness.sh | LOC <= MAX_LOC_PER_CYCLE |\n"
    + "\n"
    + "HITL: Edit `GOAL.md` to add project-specific axes (e.g.,\n"
    + "`a11y >= 0.9` or `perf_budget_p99 < 200ms`). Each axis is a\n"
    + "separate instrument script.\n"
    + "\n"
    + "## After the loop terminates\n"
    + "\n"
    + "```bash\n"
    + "PROJECT_DIR=$(pwd) ./verifiers/private/grader.sh\n"
    + "cat logs/held-out-score.json\n"
    + "```\n"
    + "\n"
    + "The held-out score is the *real* measure. The design-set\n"
    + "score is the development signal.\n"
    + "\n"
    + "## Goal summary\n"
    + "\n"
    + "(One-paragraph summary extracted from GOAL.md.)\n"
    + "\n"
    + "> " + (goal_summary[:200] if goal_summary else "(see GOAL.md)") + "...\n"
)

INSTRUMENT_FILES = {
    "time-remaining.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print seconds remaining since the loop started.\n"
        + "set -euo pipefail\n"
        + 'STATE_FILE="${PROJECT_DIR:-.}/logs/.loop_start_ts"\n'
        + 'if [[ "${1:-}" == "--set" ]]; then\n'
        + '  date +%s > "$STATE_FILE"\n'
        + '  echo "loop start set: $(cat "$STATE_FILE")"\n'
        + "  exit 0\n"
        + "fi\n"
        + 'if [[ ! -s "$STATE_FILE" ]]; then\n'
        + '  date +%s > "$STATE_FILE"\n'
        + "fi\n"
        + 'START=$(cat "$STATE_FILE")\n'
        + "NOW=$(date +%s)\n"
        + 'WALL_BUDGET="${WALL_BUDGET_SECONDS:-21600}"\n'
        + "echo $(( WALL_BUDGET - (NOW - START) ))\n"
    ),
    "tokens-remaining.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print tokens remaining out of TOKEN_BUDGET (default 200k).\n"
        + "set -euo pipefail\n"
        + 'USED_FILE="${PROJECT_DIR:-.}/logs/tokens_used.txt"\n'
        + 'BUDGET="${TOKEN_BUDGET:-200000}"\n'
        + "USED=0\n"
        + '[[ -s "$USED_FILE" ]] && USED=$(cat "$USED_FILE")\n'
        + "echo $(( BUDGET - USED ))\n"
    ),
    "tokens-this-iter.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print tokens used in the last cycle.\n"
        + "set -euo pipefail\n"
        + 'F="${PROJECT_DIR:-.}/logs/tokens_last_cycle.txt"\n'
        + '[[ -s "$F" ]] && cat "$F" || echo 0\n'
    ),
    "cline-version.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print installed Cline version.\n"
        + "set -euo pipefail\n"
        + 'CLINE_BIN="${CLINE_BIN:-$(command -v cline 2>/dev/null || true)}"\n'
        + 'if [[ -z "$CLINE_BIN" || ! -x "$CLINE_BIN" ]]; then\n'
        + '  echo "cline not found" >&2\n'
        + "  exit 1\n"
        + "fi\n"
        + '"$CLINE_BIN" --version\n'
    ),
    "cline-skills-dir.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print the directory Cline scans for skills.\n"
        + "set -euo pipefail\n"
        + 'CLINE_DATA_DIR="${CLINE_DATA_DIR:-$HOME/.cline}"\n'
        + 'echo "CLINE_DATA_DIR=$CLINE_DATA_DIR"\n'
        + 'echo "SKILLS_DIR=$CLINE_DATA_DIR/skills"\n'
        + 'echo "---"\n'
        + 'echo "Each skill is a directory containing SKILL.md with"\n'
        + 'echo "YAML frontmatter. Required fields vary by Cline version."\n'
    ),
    "sub-loss-readout.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print per-cycle sub-losses as JSON.\n"
        + "# Usage: sub-loss-readout.sh <cycle-N.json>\n"
        + "set -euo pipefail\n"
        + 'CYCLE_JSON="${1:?usage: sub-loss-readout.sh <cycle-N.json>}"\n'
        + 'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"\n'
        + 'python3 "$SCRIPT_DIR/../compute_sub_losses.py" "$CYCLE_JSON"\n'
    ),
    "test-freshness.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Assert the visible test set has not been modified since the\n"
        + "# last cycle. The agent must not be able to change a test to\n"
        + "# pass it. Stores the SHA-256 of the design set on first run,\n"
        + "# compares on subsequent runs.\n"
        + "#\n"
        + "# Usage: test-freshness.sh [--record]\n"
        + "#   (no flag): compare current SHA to recorded; exit 1 if changed.\n"
        + "#   --record:  record the current SHA as the baseline.\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + 'STATE_DIR="${PROJECT_DIR}/logs"\n'
        + 'FRESHNESS_FILE="${STATE_DIR}/.test-freshness.sha256"\n'
        + 'TASK_ROOT="${PROJECT_DIR}/test-tasks/design"\n'
        + '[[ -d "$TASK_ROOT" ]] || { echo "no design set at $TASK_ROOT" >&2; exit 1; }\n'
        + 'CURRENT=$(find "$TASK_ROOT" -type f -name "grade.sh" -o -name "prompt.txt" \\\n'
        + '             -o -name "README.md" 2>/dev/null | sort \\\n'
        + '             | xargs -I {} shasum -a 256 {} 2>/dev/null \\\n'
        + '             | shasum -a 256 | awk "{print \\$1}")\n'
        + 'if [[ "${1:-}" == "--record" ]]; then\n'
        + '  mkdir -p "$STATE_DIR"\n'
        + '  echo "$CURRENT" > "$FRESHNESS_FILE"\n'
        + '  echo "recorded: $CURRENT"\n'
        + '  exit 0\n'
        + 'fi\n'
        + 'if [[ ! -s "$FRESHNESS_FILE" ]]; then\n'
        + '  echo "no baseline recorded; pass-through (first cycle)" >&2\n'
        + '  exit 0\n'
        + 'fi\n'
        + 'PRIOR=$(cat "$FRESHNESS_FILE")\n'
        + 'if [[ "$PRIOR" != "$CURRENT" ]]; then\n'
        + '  echo "FAIL: design set modified since last cycle" >&2\n'
        + '  echo "  prior:    $PRIOR" >&2\n'
        + '  echo "  current:  $CURRENT" >&2\n'
        + '  exit 1\n'
        + 'fi\n'
        + 'echo "ok: design set unchanged ($CURRENT)"\n'
    ),
    "hidden-unread.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Assert the agent's last-cycle transcript contains no references\n"
        + "# to the held-out test directory or the private grader. The agent\n"
        + "# must not be reading the exam.\n"
        + "#\n"
        + "# Usage: hidden-unread.sh <file> [<file>...]\n"
        + "# Exits 0 if none of the supplied agent-output files contain a\n"
        + "# reference to the held-out surface (h01..hNN) or to the private\n"
        + "# grader paths. Exits 1 on any leak.\n"
        + "#\n"
        + "# The loop (cycle.sh) passes only the files the agent produced\n"
        + "# (wrapper.stderr, transcript.txt, .iterations/<cycle>/*). It does\n"
        + "# NOT pass cycle-summary.json, input.json, or prompt.txt, which\n"
        + "# are the loop's own writes (they echo the loop's prompt and\n"
        + "# would trigger false positives on the verifiers/private rule).\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + '# Collect names from the held-out surface (h01..h10, private paths).\n'
        + 'HELD_OUT_DIR="${PROJECT_DIR}/test-tasks/held-out"\n'
        + 'HELD_OUT_NAMES=$(\n'
        + '  [[ -d "$HELD_OUT_DIR" ]] && find "$HELD_OUT_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \\; 2>/dev/null\n'
        + ')\n'
        + 'PRIVATE_PATTERNS="verifiers/private|chmod 600|chmod 700"\n'
        + '# Accept one or more files as args. Each is an agent-output file\n'
        + '# (NOT the loop\'s own writes like cycle-summary.json, which echoes\n'
        + '# the loop\'s prompt and would trigger false positives).\n'
        + '[[ $# -lt 1 ]] && { echo "usage: hidden-unread.sh <file> [<file>...]" >&2; exit 2; }\n'
        + 'SCAN_FILES=("$@")\n'
        + 'SCAN_TEXT="\n"\n'
        + 'for f in "${SCAN_FILES[@]}"; do\n'
        + '  [[ -f "$f" ]] || continue\n'
        + '  SCAN_TEXT="${SCAN_TEXT}$(cat "$f" 2>/dev/null || true)\n"\n'
        + 'done\n'
        + '[[ -n "$SCAN_TEXT" && "$SCAN_TEXT" != $''\n'' ]] || { echo "no agent transcript content" >&2; exit 0; }\n'
        + '# Check private path patterns.\n'
        + 'if echo "$SCAN_TEXT" | grep -qE "$PRIVATE_PATTERNS"; then\n'
        + '  echo "FAIL: transcript references the private grader surface" >&2\n'
        + '  echo "$SCAN_TEXT" | grep -nE "$PRIVATE_PATTERNS" | head -5 >&2\n'
        + '  exit 1\n'
        + 'fi\n'
        + '# Check each held-out task name.\n'
        + 'for name in $HELD_OUT_NAMES; do\n'
        + '  if echo "$SCAN_TEXT" | grep -qF "$name"; then\n'
        + '    echo "FAIL: transcript references held-out task $name" >&2\n'
        + '    echo "$SCAN_TEXT" | grep -nF "$name" | head -5 >&2\n'
        + '    exit 1\n'
        + '  fi\n'
        + 'done\n'
        + 'echo "ok: transcript contains no references to held-out or private surfaces"\n'
    ),
    "smallness.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/smallness.sh - code-quality\n"
        + f"# Soft reward: penalizes candidates that exceed the LOC budget.\n"
        + f"# Parses MAX_LOC_PER_CYCLE from GOAL.md (default 200).\n"
        + f"#\n"
        + f"# Score: 1.0 if LOC <= budget, linear decay to 0.5 at 2x budget, 0.0 above.\n"
        + f"# This is a real (non-stub) measurement. No HITL required.\n"
        + f"#\n"
        + f"# What it counts: lines in skills/<artifact>/ and test-tasks/.\n"
        + f"#\n"
        + f"# Usage: smallness.sh\n"
        + f"#   Prints a float in [0.0, 1.0].\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"' + "\n"
        + 'BUDGET=$(python3 - "$PROJECT_DIR/GOAL.md" 2>/dev/null <<\'PY\'\n'
        + "import re, sys\n"
        + "try:\n"
        + "    text = open(sys.argv[1]).read()\n"
        + "    m = re.search(r'MAX_LOC_PER_CYCLE[ \\t]*=[ \\t]*([0-9]+)', text)\n"
        + "    print(m.group(1) if m else '200')\n"
        + "except Exception:\n"
        + "    print('200')\n"
        + "PY\n"
        + ")\n"
        + "\n"
        + "LOC=0\n"
        + 'for d in "$PROJECT_DIR/skills" "$PROJECT_DIR/test-tasks"; do' + "\n"
        + '  [[ -d "$d" ]] || continue' + "\n"
        + '  while IFS= read -r f; do' + "\n"
        + '    [[ -f "$f" ]] && LOC=$((LOC + $(wc -l < "$f" 2>/dev/null || echo 0)))' + "\n"
        + '  done < <(find "$d" -type f 2>/dev/null)' + "\n"
        + "done\n"
        + "\n"
        + "python3 - \"$BUDGET\" \"$LOC\" <<'PY'\n"
        + "import sys\n"
        + "budget = int(sys.argv[1])\n"
        + "loc = int(sys.argv[2])\n"
        + "if loc <= budget:\n"
        + "    print(1.0)\n"
        + "elif loc <= 2 * budget:\n"
        + "    print(round(1.0 - 0.5 * (loc - budget) / budget, 4))\n"
        + "else:\n"
        + "    print(0.0)\n"
        + "PY\n"
    ),
    "per-cycle-wall-clock.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print seconds spent in the most recent cycle. Records the\n"
        + "# wall-clock per cycle so the loop can reward fast-improving\n"
        + "# cycles and penalize slow ones (the smallness / speed signal).\n"
        + "#\n"
        + "# Usage: per-cycle-wall-clock.sh [--record SECONDS] | (no flag = read latest)\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + 'STATE_DIR="${PROJECT_DIR}/logs"\n'
        + 'CLOCK_FILE="${STATE_DIR}/.per-cycle-wall-clock.tsv"\n'
        + 'if [[ "${1:-}" == "--record" ]]; then\n'
        + '  SEC="${2:?usage: per-cycle-wall-clock.sh --record SECONDS [CYCLE]}"\n'
        + '  CYCLE="${3:-$(date +%s)}"\n'
        + '  mkdir -p "$STATE_DIR"\n'
        + '  echo -e "${CYCLE}\\t${SEC}" >> "$CLOCK_FILE"\n'
        + '  echo "recorded: cycle=$CYCLE sec=$SEC"\n'
        + '  exit 0\n'
        + 'fi\n'
        + '[[ -s "$CLOCK_FILE" ]] || { echo 0; exit 0; }\n'
        + 'tail -1 "$CLOCK_FILE" | awk -F"\\t" "{print \\$2}"\n'
    ),
    "linter.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/linter.sh - code-quality\n"
        + f"# Linter pass rate on the candidate. 1.0 if the linter is clean, 0.0 if it failed.\n"
        + f"#\n"
        + f"# Tool hint: eslint, golangci-lint, ruff, rubocop, pylint, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: linter.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "type-check.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/type-check.sh - code-quality\n"
        + f"# Type checker pass rate. 1.0 if the type checker is clean.\n"
        + f"#\n"
        + f"# Tool hint: tsc --noEmit, mypy, go build, cargo check, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: type-check.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "complexity.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/complexity.sh - code-quality\n"
        + f"# Cyclomatic complexity under the project threshold. Returns 1.0 if max is under threshold.\n"
        + f"#\n"
        + f"# Tool hint: lizard, radon cc, gocyclo, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: complexity.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "unit-tests.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/unit-tests.sh - tests\n"
        + f"# Unit test pass rate on the candidate. 1.0 = all pass, 0.0 = all fail.\n"
        + f"#\n"
        + f"# Tool hint: pytest, go test, jest, vitest, cargo test, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: unit-tests.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "integration-tests.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/integration-tests.sh - tests\n"
        + f"# Integration test pass rate.\n"
        + f"#\n"
        + f"# Tool hint: pytest --integration, go test -tags=integration, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: integration-tests.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "test-coverage.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/test-coverage.sh - tests\n"
        + f"# Test coverage. 1.0 if coverage >= threshold, partial credit below.\n"
        + f"#\n"
        + f"# Tool hint: coverage.py, jacoco, istanbul, go test -cover, cargo tarpaulin.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: test-coverage.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "mutation-tests.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/mutation-tests.sh - tests\n"
        + f"# Mutation score. 1.0 if all mutants are killed.\n"
        + f"#\n"
        + f"# Tool hint: mutmut, go-mutesting, stryker, pitest.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: mutation-tests.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "e2e-tests.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/e2e-tests.sh - tests\n"
        + f"# End-to-end smoke test pass rate.\n"
        + f"#\n"
        + f"# Tool hint: playwright, cypress, selenium, k6, autocannon, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: e2e-tests.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "regression-tests.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/regression-tests.sh - tests\n"
        + f"# Known-bug regression suite. 1.0 if no known regression recurs.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. The user defines a regressions/ directory with reproduction tests.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: regression-tests.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "contract-tests.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/contract-tests.sh - tests\n"
        + f"# API contract / schema validation pass rate.\n"
        + f"#\n"
        + f"# Tool hint: pact, schemathesis, openapi-validator, json-schema, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: contract-tests.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "secret-scan.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/secret-scan.sh - security\n"
        + f"# Secret scan pass rate. 1.0 if no secrets are committed.\n"
        + f"#\n"
        + f"# Tool hint: gitleaks, trufflehog, detect-secrets.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: secret-scan.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "sast.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/sast.sh - security\n"
        + f"# Static Application Security Testing. 1.0 if no high-severity issues.\n"
        + f"#\n"
        + f"# Tool hint: semgrep, codeql, snyk code, sonarqube.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: sast.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "dependency-audit.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/dependency-audit.sh - security\n"
        + f"# Dependency vulnerability audit. 1.0 if no known-vulnerable deps.\n"
        + f"#\n"
        + f"# Tool hint: npm audit, pip-audit, go list -m all, snyk test, trivy.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: dependency-audit.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "sbom.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/sbom.sh - security\n"
        + f"# Software Bill of Materials generated. 1.0 if SBOM is on disk and valid.\n"
        + f"#\n"
        + f"# Tool hint: syft, cyclonedx, spdx-sbom-generator.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: sbom.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "a11y.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/a11y.sh - quality-ux\n"
        + f"# Accessibility check. 1.0 if WCAG 2.1 AA passes.\n"
        + f"#\n"
        + f"# Tool hint: axe-core, pa11y, lighthouse --accessibility, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: a11y.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "i18n.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/i18n.sh - quality-ux\n"
        + f"# i18n completeness. 1.0 if no hardcoded user-facing strings.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. Check for hardcoded strings in templates/JSX/HTML.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: i18n.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "docs-coverage.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/docs-coverage.sh - quality-ux\n"
        + f"# Doc coverage on the public surface. 1.0 if every public symbol has a docstring.\n"
        + f"#\n"
        + f"# Tool hint: interrogate, pdoc, godoc, jsdoc, etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: docs-coverage.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "observability.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/observability.sh - observability\n"
        + f"# Structured logs / metrics / traces present. 1.0 if all three are wired.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. Check for log/metric/trace calls in handlers.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: observability.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "trace-coverage.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/trace-coverage.sh - observability\n"
        + f"# Every request handler has a trace span. 1.0 if so.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. Static analysis of handler coverage by tracing lib.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: trace-coverage.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "perf-budget.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/perf-budget.sh - performance\n"
        + f"# Performance under budget. 1.0 if p99 latency <= budget, partial credit below.\n"
        + f"#\n"
        + f"# Tool hint: k6, autocannon, wrk, vegeta, go test -bench.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: perf-budget.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "bundle-size.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/bundle-size.sh - performance\n"
        + f"# Bundle size under budget. 1.0 if bundle <= budget_kb.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. Webpack/Vite/Rollup emit size; Go binary size; etc.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: bundle-size.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "startup-time.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/startup-time.sh - performance\n"
        + f"# Cold start time under budget. 1.0 if cold_start <= budget_ms.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. Measure process startup or container readiness.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: startup-time.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "hermeticity.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/hermeticity.sh - reliability\n"
        + f"# Unit tests have no network calls. 1.0 if hermetic.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. Use iptables, toxiproxy, or mock at the test level.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: hermeticity.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "determinism.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/determinism.sh - reliability\n"
        + f"# Same input -> same output across N runs. 1.0 if deterministic.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. Re-run the candidate N times, compare outputs.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: determinism.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "flakiness.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/flakiness.sh - reliability\n"
        + f"# No flaky tests in the last N runs. 1.0 if 0 flaky tests detected.\n"
        + f"#\n"
        + f"# Tool hint: Project-specific. Track pass-rate variance per test across runs.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: flakiness.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "license-audit.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/license-audit.sh - compliance\n"
        + f"# License compatibility. 1.0 if no copyleft or unknown licenses.\n"
        + f"#\n"
        + f"# Tool hint: licensee, fossology, syft --license.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: license-audit.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

    "supply-chain.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + f"# verifiers/instruments/supply-chain.sh - compliance\n"
        + f"# SLSA / in-toto provenance present. 1.0 if signed and verified.\n"
        + f"#\n"
        + f"# Tool hint: slsa-verifier, in-toto-verify, sigstore cosign.\n"
        + f"#\n"
        + f"# This is a stub. The default returns 0.0. Wire your\n"
        + f"# real tool invocation in the section marked HITL below.\n"
        + f"#\n"
        + f"# Output: float in [0.0, 1.0]\n"
        + f"# Exit code: 0 on measurement present, non-zero on tool error.\n"
        + f"#\n"
        + f"# Usage: supply-chain.sh\n"
        + "set -euo pipefail\n"
        + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
        + "\n"
        + f"# ----- HITL: wire your tool here -----\n"
        + f"# Replace the next 3-5 lines with the real tool invocation.\n"
        + f"# The variable MEASUREMENT should be a number in [0.0, 1.0]\n"
        + f"# (1.0 = pass, 0.0 = fail, anything in between is partial credit).\n"
        + f"# Exit non-zero ONLY on tool error (not on constraint violation).\n"
        + "MEASUREMENT=0.0\n"
        + "\n"
        + f"# ----- end HITL -----\n"
        + "\n"
        + f"echo \"$MEASUREMENT\"\n"
    ),

}

PARSE_CLINE_OUTPUT_STUB = (
    GENERATED_HEADER
    + "#!/usr/bin/env python3\n"
    + '"""Minimal Cline NDJSON parser stub. Replace with the full\n'''
    "implementation from the cline-orchestration skill's scripts/\n"
    "directory, or call `harness-scaffold --update-parser` if such\n"
    "a flag exists in a future version.\"\"\"\n"
    + "from __future__ import annotations\n"
    + "import json, sys\n"
    + "from pathlib import Path\n"
    + "\n"
    + "def main(path):\n"
    + "    p = Path(path)\n"
    + "    if not p.exists() or p.stat().st_size == 0:\n"
    + '        print(json.dumps({"tokens": 0, "duration_ms": 0, "candidate_text": "",\n'
    + '                         "model": "", "provider": "", "finish_reason": "no_output",\n'
    + '                         "iterations": 0, "tool_calls": []}, indent=2))\n'
    + "        return\n"
    + "    tokens = duration_ms = 0\n"
    + '    candidate_text = model = provider = finish_reason = ""\n'
    + "    iterations = 0\n"
    + "    tool_calls = []\n"
    + "    with p.open() as f:\n"
    + "        for line in f:\n"
    + '            line = line.strip()\n'
    + "            if not line:\n"
    + "                continue\n"
    + "            try:\n"
    + "                obj = json.loads(line)\n"
    + "            except json.JSONDecodeError:\n"
    + "                continue\n"
    + '            if obj.get("type") == "run_result":\n'
    + '                agg = obj.get("aggregateUsage") or {}\n'
    + "                tokens = (\n"
    + "                    int(agg.get('inputTokens', 0) or 0)\n"
    + "                    + int(agg.get('outputTokens', 0) or 0)\n"
    + "                    + int(agg.get('cacheReadTokens', 0) or 0)\n"
    + "                )\n"
    + "                duration_ms = int(obj.get('durationMs', 0) or 0)\n"
    + "                candidate_text = obj.get('text', '') or ''\n"
    + "                finish_reason = obj.get('finishReason', '')\n"
    + "                iterations = int(obj.get('iterations', 0) or 0)\n"
    + '                m = obj.get("model") or {}\n'
    + '                model = m.get("id", ""); provider = m.get("provider", "")\n'
    + '    print(json.dumps({"tokens": tokens, "duration_ms": duration_ms,\n'
    + '                         "candidate_text": candidate_text,\n'
    + '                         "model": model, "provider": provider,\n'
    + '                         "finish_reason": finish_reason,\n'
    + '                         "iterations": iterations,\n'
    + '                         "tool_calls": tool_calls}, indent=2))\n'
    + "\n"
    + 'if __name__ == "__main__":\n'
    + "    main(sys.argv[1])\n"
)

COMPUTE_SUB_LOSSES_STUB = (
    GENERATED_HEADER
    + "#!/usr/bin/env python3\n"
    + '"""Per-cycle sub-loss scorer stub. Replace with the full\n'''
    "implementation from the cline-orchestration skill's references/\n"
    "directory, or implement your own 7 sub-losses using the\n"
    "WEIGHTS / GATES constants below as a starting point.\n"
    '"""\n'
    + "from __future__ import annotations\n"
    + "import json, sys\n"
    + "from pathlib import Path\n"
    + "\n"
    + "WEIGHTS = {\n"
    + '    "correctness": 1.0,\n'
    + '    "performance": 0.5,\n'
    + '    "safety": 1.0,\n'
    + '    "legibility": 0.3,\n'
    + '    "invariants": 1.0,\n'
    + '    "drift": 0.2,\n'
    + '    "cost": 0.3,\n'
    + "}\n"
    + 'GATES = {"correctness", "safety", "invariants"}\n'
    + "\n"
    + "def main(path):\n"
    + "    p = Path(path)\n"
    + "    if not p.exists():\n"
    + '        print(json.dumps({"error": f"cycle json not found: {path}"}))\n'
    + "        return\n"
    + "    raw = {}\n"
    + "    try:\n"
    + "        raw = json.loads(p.read_text())\n"
    + "    except json.JSONDecodeError:\n"
    + "        for line in p.read_text().splitlines():\n"
    + "            try:\n"
    + "                obj = json.loads(line.strip())\n"
    + '                if obj.get("type") == "run_result":\n'
    + '                    agg = obj.get("aggregateUsage") or {}\n'
    + "                    raw = {\n"
    + '                        "tokens": int(agg.get("inputTokens", 0) or 0) + int(agg.get("outputTokens", 0) or 0),\n'
    + '                        "elapsed_seconds": int(obj.get("durationMs", 0) or 0) // 1000,\n'
    + '                        "finish_reason": obj.get("finishReason", ""),\n'
    + '                        "exit_code": 0,\n'
    + '                        "candidate_text": obj.get("text", ""),\n'
    + '                        "model": (obj.get("model") or {}).get("id", ""),\n'
    + "                    }\n"
    + "                    break\n"
    + "            except json.JSONDecodeError:\n"
    + "                continue\n"
    + "    scores = {\n"
    + '        "correctness": 1.0 if raw.get("exit_code") == 0 and raw.get("candidate_text", "").strip() else 0.0,\n'
    + '        "performance": 1.0 if raw.get("elapsed_seconds", 999) <= 90 else 0.0,\n'
    + '        "safety": 1.0,\n'
    + '        "legibility": 1.0 if len(raw.get("candidate_text", "")) >= 10 else 0.3,\n'
    + '        "invariants": 1.0 if raw.get("exit_code") == 0 and raw.get("finish_reason") == "completed" else 0.0,\n'
    + '        "drift": 1.0,\n'
    + '        "cost": 1.0 if raw.get("tokens", 0) <= 4000 else 0.0,\n'
    + "    }\n"
    + '    out = {"sub_losses": {k: {"score": v, "details": {}} for k, v in scores.items()},\n'
    + '           "weights": WEIGHTS, "gates": list(GATES),\n'
    + '           "weighted_sum": sum(scores[k] * WEIGHTS[k] for k in scores),\n'
    + '           "weighted_total": sum(WEIGHTS.values()),\n'
    + '           "gates_passed": all(scores[g] >= 1.0 for g in GATES)}\n'
    + '    out["weighted_normalized"] = round(out["weighted_sum"] / out["weighted_total"], 4)\n'
    + "    print(json.dumps(out, indent=2))\n"
    + "\n"
    + 'if __name__ == "__main__":\n'
    + "    if len(sys.argv) < 2:\n"
    + '        print("usage: compute_sub_losses.py <cycle-N.json>", file=sys.stderr)\n'
    + "        sys.exit(2)\n"
    + "    main(sys.argv[1])\n"
)

CLINE_WRAPPER_SH = (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# cline-wrapper.sh — the ONLY way to invoke cline inside\n"
    + "# the loss loop.\n"
    + "#\n"
    + "# Usage:\n"
    + '#   verifiers/cline-wrapper.sh "<task-prompt>" --cwd PATH \\\n'
    + "#       --timeout 600 --cycle cycle-1 > cycle-1.json\n"
    + "#\n"
    + "# Why these flags:\n"
    + "# - --thinking none: many OpenAI-compat endpoints reject\n"
    + "#   the reasoning-token request shape. Change per provider.\n"
    + "# - --auto-approve true: required for non-interactive file\n"
    + "#   work. Safety is enforced by a separate transcript grep.\n"
    + "# - No --worktree: per-cycle directory already gives\n"
    + "#   isolation; --worktree triggers auth failures.\n"
    + "\n"
    + "set -euo pipefail\n"
    + "\n"
    + 'TASK=""; CWD=""; TIMEOUT=600; CYCLE="cycle-0"\n'
    + "while [[ $# -gt 0 ]]; do\n"
    + '  case "$1" in\n'
    + '    --cwd) CWD="$2"; shift 2 ;;\n'
    + '    --timeout) TIMEOUT="$2"; shift 2 ;;\n'
    + '    --cycle)\n'
    + '      if [[ "${2:-}" =~ ^[0-9]+$ ]]; then CYCLE="cycle-$2"; shift 2\n'
    + '      else CYCLE="${2:-cycle-0}"; shift 2; fi ;;\n'
    + '    --cycle=*) CYCLE="${1#--cycle=}"; shift ;;\n'
    + '    *) TASK="$1"; shift ;;\n'
    + "  esac\n"
    + "done\n"
    + '[[ -z "$TASK" || -z "$CWD" ]] && {\n'
    + '  echo \'{"error":"missing arg"}\' >&2; exit 2;\n'
    + "}\n"
    + "\n"
    + '# Resolve cline binary: $CLINE_BIN env, then PATH, then bail.\n'
    + 'CLINE_BIN="${CLINE_BIN:-$(command -v cline 2>/dev/null || true)}"\n'
    + '[[ -z "$CLINE_BIN" || ! -x "$CLINE_BIN" ]] && {\n'
    + '  echo \'{"error":"cline not found"}\' >&2; exit 3;\n'
    + "}\n"
    + "\n"
    + 'ITER_DIR="${CWD}/.iterations/${CYCLE}"\n'
    + 'mkdir -p "$ITER_DIR"\n'
    + "\n"
    + "# Seed the iter dir with the task's source files (so Cline\n"
    + "# has the actual problem to work on).\n"
    + "if command -v rsync >/dev/null 2>&1; then\n"
    + '  rsync -a --exclude=".iterations/" --exclude=".git/" \\\n'
    + '        --exclude="*.stderr" --exclude="cline.json" \\\n'
    + '        --exclude="cycle-summary.json" \\\n'
    + '        "$CWD"/ "$ITER_DIR"/ 2>/dev/null || true\n'
    + "else\n"
    + '  find "$CWD" -mindepth 1 -maxdepth 1 \\\n'
    + '       -not -name ".iterations" -not -name ".git" \\\n'
    + '       -exec cp -R {} "$ITER_DIR"/ \\; 2>/dev/null || true\n'
    + "fi\n"
    + "\n"
    + "START_TS=$(date +%s)\n"
    + 'RAW_OUT="${ITER_DIR}/cline.json"\n'
    + "EXIT_CODE=0\n"
    + "\n"
    + '"$CLINE_BIN" "$TASK" \\\n'
    + '  --cwd "$ITER_DIR" \\\n'
    + '  --auto-approve true \\\n'
    + '  --thinking none \\\n'
    + '  --json \\\n'
    + '  > "$RAW_OUT" 2>"${ITER_DIR}/cline.stderr" || EXIT_CODE=$?\n'
    + "\n"
    + "END_TS=$(date +%s)\n"
    + "ELAPSED=$((END_TS - START_TS))\n"
    + "\n"
    + 'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"\n'
    + 'PARSED=$(python3 "$SCRIPT_DIR/parse_cline_output.py" "$RAW_OUT")\n'
    + "\n"
    + "python3 -c '\n"
    + "import json, sys\n"
    + "out = json.loads(sys.argv[1])\n"
    + 'out.update({\n'
    + '    "cycle": sys.argv[2],\n'
    + '    "exit_code": int(sys.argv[3]),\n'
    + '    "elapsed_seconds": int(sys.argv[4]),\n'
    + '    "raw_output_path": sys.argv[5],\n'
    + "})\n"
    + 'print(json.dumps(out, indent=2))\n'
    + "' \"$PARSED\" \"$CYCLE\" \"$EXIT_CODE\" \"$ELAPSED\" \"$RAW_OUT\"\n"
)

RUN_DESIGN_SET_SH = lambda design_task_names: (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# verifiers/run-design-set.sh\n"
    + "# Run the wrapper + per-task grader for every design task\n"
    + "# and emit an aggregate JSON score.\n"
    + "\n"
    + "set -euo pipefail\n"
    + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
    + 'CYCLE="${CYCLE:-design-set-cycle-$(date +%s)}"\n'
    + 'RUNS_DIR="$PROJECT_DIR/logs/design-set-runs/$CYCLE"\n'
    + 'SCORE_FILE="$PROJECT_DIR/logs/design-set-score.json"\n'
    + 'mkdir -p "$RUNS_DIR"\n'
    + "\n"
    + "TASKS=(\n"
    + "".join('  "%s"\n' % t for t in design_task_names)
    + ")\n"
    + "\n"
    + "n_pass=0; n_total=0; total_tokens=0\n"
    + "results=()\n"
    + "\n"
    + "for task in \"${TASKS[@]}\"; do\n"
    + "  n_total=$((n_total + 1))\n"
    + '  task_dir="$PROJECT_DIR/test-tasks/design/$task"\n'
    + '  task_run_dir="$RUNS_DIR/$task"\n'
    + '  mkdir -p "$task_run_dir"\n'
    + "\n"
    + '  if [[ ! -d "$task_dir" ]]; then\n'
    + '    results+=("{\\"task\\":\\"$task\\",\\"status\\":\\"missing\\",\\"detail\\":\\"no task dir\\"}")\n'
    + "    continue\n"
    + "  fi\n"
    + "\n"
    + '  if [[ -f "$task_dir/prompt.txt" ]]; then\n'
    + '    prompt="$(cat "$task_dir/prompt.txt")"\n'
    + "  else\n"
    + '    prompt="Look at the files in this directory and complete the task described in the README."\n'
    + "  fi\n"
    + "\n"
    + '  iter_dir="$task_dir/.iterations/$CYCLE"\n'
    + '  mkdir -p "$iter_dir"\n'
    + '  task_cycle="cycle-$(date +%s)-$task"\n'
    + "\n"
    + '  echo "[run-design-set] running wrapper for $task ..." >&2\n'
    + '  if "$PROJECT_DIR/verifiers/cline-wrapper.sh" "$prompt" \\\n'
    + '       --cwd "$task_dir" --timeout 180 --cycle "$task_cycle" \\\n'
    + '       > "$task_run_dir/cycle-summary.json" 2>"$task_run_dir/wrapper.stderr"; then\n'
    + "    :\n"
    + "  else\n"
    + '    echo "[run-design-set] wrapper failed for $task (exit $?)" >&2\n'
    + "  fi\n"
    + "\n"
    + '  rm -rf "$task_run_dir/iter"\n'
    + '  if [[ -d "$task_dir/.iterations" ]]; then\n'
    + '    latest_iter="$(ls -1t "$task_dir/.iterations" | head -1)"\n'
    + '    if [[ -n "$latest_iter" ]]; then\n'
    + '      mv "$task_dir/.iterations/$latest_iter" "$task_run_dir/iter" 2>/dev/null || true\n'
    + "    fi\n"
    + "  fi\n"
    + "\n"
    + '  if [[ -x "$task_dir/grade.sh" ]]; then\n'
    + '    if "$task_dir/grade.sh" "$task_run_dir/iter" > "$task_run_dir/grade.txt" 2>&1; then\n'
    + '      n_pass=$((n_pass + 1)); grade_status="pass"\n'
    + "    else\n"
    + '      grade_status="fail"\n'
    + "    fi\n"
    + "  else\n"
    + '    grade_status="missing"\n'
    + "  fi\n"
    + "\n"
    + '  tok=0\n'
    + '  if [[ -s "$task_run_dir/cycle-summary.json" ]]; then\n'
    + '    tok=$(python3 -c "import json; print(int(json.load(open('"'"'"$task_run_dir/cycle-summary.json"'"'"' )).get('"'"'tokens'"'"',0) or 0))" 2>/dev/null || echo 0)\n'
    + "  fi\n"
    + '  total_tokens=$((total_tokens + tok))\n'
    + '  results+=("{\\"task\\":\\"$task\\",\\"status\\":\\"$grade_status\\",\\"tokens\\":$tok}")\n'
    + "done\n"
    + "\n"
    + 'pass_rate=$(python3 -c "print(round($n_pass / max($n_total, 1), 4))")\n'
    + "python3 -c \"\n"
    + "import json\n"
    + "score = {\n"
    + "    'cycle': '$CYCLE',\n"
    + "    'n_pass': $n_pass,\n"
    + "    'n_total': $n_total,\n"
    + "    'pass_rate': $pass_rate,\n"
    + "    'total_tokens': $total_tokens,\n"
    + "}\n"
    + 'print(json.dumps(score, indent=2))\n'
    + "\" > \"$SCORE_FILE\"\n"
    + 'cat "$SCORE_FILE"\n'
)

DESIGN_PROMPT_STUB = lambda task_desc: (
    GENERATED_HEADER
    + "\n"
    + "# " + task_desc + "\n"
    + "\n"
    + "(Write a 1-2 sentence description of the task here. The\n"
    + "agent reads this as the prompt.)\n"
)

DESIGN_README_STUB = lambda task_desc: (
    GENERATED_HEADER
    + "\n"
    + "# " + task_desc + "\n"
    + "\n"
    + "(Describe the task in detail: the input shape, the expected\n"
    + "output, and any edge cases. The grader uses this for\n"
    + "context.)\n"
)

DESIGN_GRADE_STUB = (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# TODO: write the deterministic grader for this task.\n"
    + "# Usage: grade.sh <iter-dir>\n"
    + "# Exits 0 on pass, 1 on fail.\n"
    + "set -euo pipefail\n"
    + 'ITER_DIR="${1:?usage: grade.sh <iter-dir>}"\n'
    + '[[ -d "$ITER_DIR" ]] || { echo "FAIL: not a dir" >&2; exit 1; }\n'
    + '[[ ! -d "$ITER_DIR/.iterations" ]] || { echo "FAIL: parent dir" >&2; exit 1; }\n'
    + 'echo "FAIL: grade.sh not implemented for this task yet" >&2\n'
    + "exit 1\n"
)

HELDOUT_README_STUB = lambda tid: (
    GENERATED_HEADER
    + "\n"
    + "# Held-out task " + tid + "\n"
    + "\n"
    + "This is a held-out task. The agent must NOT read this\n"
    + "directory. The grader at `verifiers/private/grader.sh`\n"
    + "runs the agent's candidate against this task.\n"
    + "\n"
    + "TODO: provide the actual task files here:\n"
    + "- the starting source file\n"
    + "- `prompt.txt` (the prompt given to the agent)\n"
    + "- `grade.sh` (the deterministic grader, chmod 700)\n"
    + "\n"
    + "The user (or a research skill) fills these in. The\n"
    + "agent's loop will only ever see the design tasks.\n"
)

PRIVATE_GRADER_STUB = (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# HELD-OUT GRADER. INTENTIONALLY hidden from the agent.\n"
    + "# The agent must NOT read this script, must NOT read any\n"
    + "# task under test-tasks/held-out/, and must NOT enumerate\n"
    + "# the contents of verifiers/private/.\n"
    + "\n"
    + "set -euo pipefail\n"
    + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
    + 'CYCLE="${CYCLE:-held-out-$(date +%s)}"\n'
    + 'RUNS_DIR="$PROJECT_DIR/logs/held-out-runs/$CYCLE"\n'
    + 'SCORE_FILE="$PROJECT_DIR/logs/held-out-score.json"\n'
    + 'mkdir -p "$RUNS_DIR"\n'
    + "\n"
    + "# TODO: enumerate the 10 held-out tasks and for each: invoke\n"
    + "# the wrapper, run the per-task grader, aggregate pass_rate.\n"
    + "\n"
    + 'echo \'{"error": "held-out grader not implemented yet"}\' > "$SCORE_FILE"\n'
    + 'cat "$SCORE_FILE"\n'
)


# ----- scaffold functions -----

def scaffold_instruments(project):
    inst = project / "verifiers" / "instruments"
    inst.mkdir(parents=True, exist_ok=True)
    for name, content in INSTRUMENT_FILES.items():
        safe_write(inst / name, content, executable=True)


def scaffold_integrity(project):
    safe_write(project / "verifiers" / "integrity.sh",
               INTEGRITY_SH, executable=True)


def scaffold_compute_sub_losses(project):
    safe_write(project / "verifiers" / "compute_sub_losses.py",
               COMPUTE_SUB_LOSSES_STUB)


def scaffold_parse_cline_output(project):
    safe_write(project / "verifiers" / "parse_cline_output.py",
               PARSE_CLINE_OUTPUT_STUB)


def scaffold_cline_wrapper(project, runtime):
    if runtime != "cline":
        content = (
            GENERATED_HEADER
            + "#!/usr/bin/env bash\n"
            + "# Wrapper for " + runtime + ".\n"
            + "# TODO: replace this stub with the appropriate\n"
            + "# invocation for your agent. See cline-orchestration\n"
            + "# skill for the pattern.\n"
            + "set -euo pipefail\n"
            + 'echo "TODO: implement ' + runtime + ' wrapper" >&2\n'
            + "exit 1\n"
        )
    else:
        content = CLINE_WRAPPER_SH
    safe_write(project / "verifiers" / "cline-wrapper.sh", content, executable=True)


def scaffold_run_design_set(project, design_task_names):
    safe_write(project / "verifiers" / "run-design-set.sh",
               RUN_DESIGN_SET_SH(design_task_names), executable=True)


def scaffold_design_task_stubs(project, tasks):
    design_dir = project / "test-tasks" / "design"
    design_dir.mkdir(parents=True, exist_ok=True)
    for i, task_desc in enumerate(tasks, 1):
        slug = word_truncate(slugify(task_desc) or f"task-{i:02d}", 40)
        task_dir = design_dir / ("%02d-%s" % (i, slug))
        task_dir.mkdir(parents=True, exist_ok=True)
        safe_write(task_dir / "prompt.txt", DESIGN_PROMPT_STUB(task_desc))
        safe_write(task_dir / "README.md", DESIGN_README_STUB(task_desc))
        safe_write(task_dir / "grade.sh", DESIGN_GRADE_STUB, executable=True)


def scaffold_held_out_placeholders(project, held_out):
    held_out_dir = project / "test-tasks" / "held-out"
    held_out_dir.mkdir(parents=True, exist_ok=True)
    for tid in held_out:
        task_dir = held_out_dir / tid
        task_dir.mkdir(parents=True, exist_ok=True)
        safe_write(task_dir / "README.md", HELDOUT_README_STUB(tid))


def scaffold_private_grader(project):
    private_dir = project / "verifiers" / "private"
    private_dir.mkdir(parents=True, exist_ok=True)
    grader = private_dir / "grader.sh"
    safe_write(grader, PRIVATE_GRADER_STUB, executable=True)
    chmod_700(private_dir)
    chmod_600(grader)


def scaffold_skill_dir(project):
    skills_dir = project / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, type=Path,
                        help="The directory to scaffold into")
    parser.add_argument("--goal-prompt", type=Path, default=None,
                        help="Path to the /goal prompt (default: <project>/GOAL.md)")
    parser.add_argument("--runtime", default=None,
                        help=("Agent runtime name. The scaffold templates this "
                              "into <runtime>-wrapper.sh, run-design-set.sh, "
                              "and AGENTS.md. Free-form; the bundle ships "
                              "adapters for cline, claude-code, codex, "
                              "hermes-agent, opencode, and fake. "
                              "(default: detected from /goal prompt)"))
    parser.add_argument("--no-private", action="store_true",
                        help="Skip the held-out grader scaffold")
    args = parser.parse_args()

    project = args.project_root.expanduser().resolve()
    project.mkdir(parents=True, exist_ok=True)

    goal_path = args.goal_prompt or (project / "GOAL.md")
    goal = goal_path.read_text() if goal_path.exists() else ""

    runtime = args.runtime or extract_runtime(goal) or "cline"
    design_tasks = extract_design_tasks(goal)
    design_names = []
    for i, t in enumerate(design_tasks, 1):
        slug = word_truncate(slugify(t) or f"task-{i:02d}", 40)
        design_names.append("%02d-%s" % (i, slug))
    held_out = extract_held_out_tasks(goal)

    print("scaffolding " + str(project), file=sys.stderr)
    print("  runtime:   " + runtime, file=sys.stderr)
    print("  design:    " + str(len(design_tasks)) + " tasks", file=sys.stderr)
    print("  held-out:  " + str(len(held_out)) + " tasks", file=sys.stderr)

    safe_write(project / "AGENTS.md", AGENTS_MD(project.name))
    safe_write(project / "README.md", README_MD(project.name, goal))
    if goal_path.exists() and goal_path != project / "GOAL.md":
        safe_write(project / "GOAL.md", goal)
    elif not (project / "GOAL.md").exists() and goal:
        safe_write(project / "GOAL.md", goal)
    scaffold_instruments(project)
    scaffold_integrity(project)
    scaffold_compute_sub_losses(project)
    scaffold_parse_cline_output(project)
    scaffold_cline_wrapper(project, runtime)
    scaffold_run_design_set(project, design_names)
    scaffold_design_task_stubs(project, design_tasks)
    scaffold_held_out_placeholders(project, held_out)
    if not args.no_private:
        scaffold_private_grader(project)
    scaffold_skill_dir(project)

    (project / "logs").mkdir(exist_ok=True)
    print("done.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
