#!/usr/bin/env python3
"""harness-scaffold — scaffold a loss-function harness tree.

Reads a /goal prompt, extracts the structured sections, and
writes the matching project tree at the project root. See
SKILL.md for the contract.

Usage:
  harness-scaffold --project-root PATH [--goal-prompt PATH] \
                   [--runtime {cline|codex|aider}] [--no-private]
"""
from __future__ import annotations

import argparse
import os
import re
import stat
import sys
from pathlib import Path
from textwrap import dedent

GENERATED_HEADER = (
    "# auto-generated by harness-scaffold v1.0\n"
    "# DO NOT EDIT — re-run `harness-scaffold` to regenerate\n"
    "# (this header marker is how the scaffold detects safe-to-overwrite files)\n"
)

AGENT_EDITED_MARKER = "# agent-edited: yes"


def is_user_edited(path):
    if not path.exists():
        return False
    try:
        with path.open() as f:
            head = "".join(f.readline() for _ in range(5))
    except Exception:
        return False
    return AGENT_EDITED_MARKER in head


def safe_write(path, content, executable=False):
    if is_user_edited(path):
        print("  skip (user-edited): " + str(path), file=sys.stderr)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        f.write(content)
    if executable:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print("  write: " + str(path), file=sys.stderr)


def chmod_700(path):
    if path.exists():
        path.chmod(0o700)


def chmod_600(path):
    if path.exists():
        path.chmod(0o600)


def extract_design_tasks(prompt):
    m = re.search(r"Design-set tasks.*?\n\n(.*?)(?=\n\n#|\Z)", prompt, re.S)
    if not m:
        return []
    block = m.group(1)
    tasks = []
    for line in block.splitlines():
        line = line.strip()
        m2 = re.match(r"^\d+\.\s+(.+)$", line)
        if not m2:
            continue
        desc = m2.group(1).strip()
        if "`" in desc:
            em = max(desc.rfind(" — "), desc.rfind(" - "))
            if em > 0:
                desc = desc[em + 3:].strip()
            else:
                m3 = re.match(r"^`[^`]+`\s*(.*)$", desc)
                if m3:
                    desc = m3.group(1).strip()
        desc = desc.strip("`'\"")
        tasks.append(desc)
    return tasks


def extract_held_out_tasks(prompt):
    m = re.search(r"Held-out tasks.*?\n\n(.*?)(?=\n\n#|\Z)", prompt, re.S)
    if not m:
        return [f"h{i:02d}" for i in range(1, 11)]
    block = m.group(1)
    range_match = re.search(
        r"(h\d{2})[^a-zA-Z0-9]{1,8}(?:…|\.{2,}|—|–|through|to| - )[^a-zA-Z0-9]{1,8}(h\d{2})",
        block, re.I,
    )
    if range_match:
        try:
            a = int(range_match.group(1)[1:])
            b = int(range_match.group(2)[1:])
            if a > b:
                a, b = b, a
            return [f"h{n:02d}" for n in range(a, b + 1)]
        except Exception:
            pass
    explicit = re.findall(r"\b(h\d{2})\b", block)
    if explicit:
        seen = set()
        out = []
        for h in explicit:
            if h not in seen:
                seen.add(h)
                out.append(h)
        return out
    return [f"h{i:02d}" for i in range(1, 11)]


def extract_runtime(prompt):
    m = re.search(r"inner loop is the `(\w+)` CLI", prompt)
    return m.group(1) if m else "cline"


def slugify(s):
    s = s.lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip("-")


def word_truncate(s, max_len):
    """Truncate at word boundary, max max_len chars."""
    if len(s) <= max_len:
        return s
    truncated = s[:max_len]
    # Find last hyphen
    last_hyphen = truncated.rfind("-")
    if last_hyphen > max_len // 2:
        return truncated[:last_hyphen]
    return truncated


# ----- file content templates -----

AGENTS_MD = lambda project_name: (
    GENERATED_HEADER
    + "\n"
    + "# AGENTS.md — loop driver rules for " + project_name + "\n"
    + "\n"
    + "Operating rules:\n"
    + "1. Read `GOAL.md` first.\n"
    + "2. Hard rules:\n"
    + "   - DO NOT read `verifiers/private/` or `test-tasks/held-out/`.\n"
    + "   - DO NOT modify `verifiers/`.\n"
    + "   - The only agent invocation is via `verifiers/cline-wrapper.sh`.\n"
    + "3. After EACH design-set run, append a one-line entry to\n"
    + "   `logs/iteration-log.md` with cycle number, hypothesis,\n"
    + "   expected failure, and pass_rate.\n"
    + "4. If pass_rate does not improve by >= 0.05, force entropy:\n"
    + "   pick the OPPOSITE of your last change, apply it, document it.\n"
    + "\n"
    + "Workflow:\n"
    + "1. Read `GOAL.md`, this file, `README.md`,\n"
    + "   `verifiers/cline-wrapper.sh`, `verifiers/run-design-set.sh`,\n"
    + "   and every script in `verifiers/instruments/`.\n"
    + "2. Read each design task's `prompt.txt` and starting file.\n"
    + "3. Establish baseline: no candidate skill installed, run\n"
    + "   `PROJECT_DIR=$(pwd) ./verifiers/run-design-set.sh`.\n"
    + "4. Begin cycle 1. Write a candidate\n"
    + "   `skills/<artifact-name>/SKILL.md` (and references).\n"
    + "5. Install the skill where the agent will pick it up.\n"
    + "6. Run `PROJECT_DIR=$(pwd) ./verifiers/run-design-set.sh` to score.\n"
    + "7. Compare to baseline. Force entropy on stall.\n"
    + "8. Iterate until one of the stop conditions in `GOAL.md` is met.\n"
    + "9. Leave the skill, references, `logs/iteration-log.md`,\n"
    + "   and `logs/best-cycle.json`.\n"
)

README_MD = lambda project_name, goal_summary: (
    GENERATED_HEADER
    + "\n"
    + "# " + project_name + "\n"
    + "\n"
    + "Loss-function-driven development project. Scaffolded by\n"
    + "`harness-scaffold` v1.0.\n"
    + "\n"
    + "## Quick start\n"
    + "\n"
    + "```bash\n"
    + "# 1. Run the design set (baseline, no skill installed yet)\n"
    + "PROJECT_DIR=$(pwd) ./verifiers/run-design-set.sh\n"
    + "cat logs/design-set-score.json\n"
    + "\n"
    + "# 2. Read AGENTS.md and follow the workflow there\n"
    + "cat AGENTS.md\n"
    + "```\n"
    + "\n"
    + "## Layout\n"
    + "\n"
    + "- `GOAL.md` — the /goal prompt this project runs against\n"
    + "- `AGENTS.md` — loop driver rules\n"
    + "- `verifiers/` — the harness\n"
    + "- `test-tasks/design/` — 5 design tasks (you can read)\n"
    + "- `test-tasks/held-out/` — 10 held-out tasks (off-limits)\n"
    + "- `skills/<artifact-name>/` — the agent's candidate skill\n"
    + "- `logs/` — the loop's running trace\n"
    + "\n"
    + "## After the loop terminates\n"
    + "\n"
    + "Run the held-out grader to get the final score:\n"
    + "\n"
    + "```bash\n"
    + "PROJECT_DIR=$(pwd) ./verifiers/private/grader.sh\n"
    + "cat logs/held-out-score.json\n"
    + "```\n"
    + "\n"
    + "The held-out score is the *real* measure. The design-set score\n"
    + "is the development signal.\n"
    + "\n"
    + "## Goal summary\n"
    + "\n"
    + "(One-paragraph summary extracted from GOAL.md.)\n"
    + "\n"
    + "> " + (goal_summary[:200] if goal_summary else "(see GOAL.md)") + "...\n"
)

INSTRUMENT_FILES = {
    "time-remaining.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print seconds remaining since the loop started.\n"
        + "set -euo pipefail\n"
        + 'STATE_FILE="${PROJECT_DIR:-.}/logs/.loop_start_ts"\n'
        + 'if [[ "${1:-}" == "--set" ]]; then\n'
        + '  date +%s > "$STATE_FILE"\n'
        + '  echo "loop start set: $(cat "$STATE_FILE")"\n'
        + "  exit 0\n"
        + "fi\n"
        + 'if [[ ! -s "$STATE_FILE" ]]; then\n'
        + '  date +%s > "$STATE_FILE"\n'
        + "fi\n"
        + 'START=$(cat "$STATE_FILE")\n'
        + "NOW=$(date +%s)\n"
        + 'WALL_BUDGET="${WALL_BUDGET_SECONDS:-21600}"\n'
        + "echo $(( WALL_BUDGET - (NOW - START) ))\n"
    ),
    "tokens-remaining.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print tokens remaining out of TOKEN_BUDGET (default 200k).\n"
        + "set -euo pipefail\n"
        + 'USED_FILE="${PROJECT_DIR:-.}/logs/tokens_used.txt"\n'
        + 'BUDGET="${TOKEN_BUDGET:-200000}"\n'
        + "USED=0\n"
        + '[[ -s "$USED_FILE" ]] && USED=$(cat "$USED_FILE")\n'
        + "echo $(( BUDGET - USED ))\n"
    ),
    "tokens-this-iter.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print tokens used in the last cycle.\n"
        + "set -euo pipefail\n"
        + 'F="${PROJECT_DIR:-.}/logs/tokens_last_cycle.txt"\n'
        + '[[ -s "$F" ]] && cat "$F" || echo 0\n'
    ),
    "cline-version.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print installed Cline version.\n"
        + "set -euo pipefail\n"
        + 'CLINE_BIN="${CLINE_BIN:-$(command -v cline 2>/dev/null || true)}"\n'
        + 'if [[ -z "$CLINE_BIN" || ! -x "$CLINE_BIN" ]]; then\n'
        + '  echo "cline not found" >&2\n'
        + "  exit 1\n"
        + "fi\n"
        + '"$CLINE_BIN" --version\n'
    ),
    "cline-skills-dir.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print the directory Cline scans for skills.\n"
        + "set -euo pipefail\n"
        + 'CLINE_DATA_DIR="${CLINE_DATA_DIR:-$HOME/.cline}"\n'
        + 'echo "CLINE_DATA_DIR=$CLINE_DATA_DIR"\n'
        + 'echo "SKILLS_DIR=$CLINE_DATA_DIR/skills"\n'
        + 'echo "---"\n'
        + 'echo "Each skill is a directory containing SKILL.md with"\n'
        + 'echo "YAML frontmatter. Required fields vary by Cline version."\n'
    ),
    "sub-loss-readout.sh": (
        GENERATED_HEADER
        + "#!/usr/bin/env bash\n"
        + "# Print per-cycle sub-losses as JSON.\n"
        + "# Usage: sub-loss-readout.sh <cycle-N.json>\n"
        + "set -euo pipefail\n"
        + 'CYCLE_JSON="${1:?usage: sub-loss-readout.sh <cycle-N.json>}"\n'
        + 'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"\n'
        + 'python3 "$SCRIPT_DIR/../compute_sub_losses.py" "$CYCLE_JSON"\n'
    ),
}

PARSE_CLINE_OUTPUT_STUB = (
    GENERATED_HEADER
    + "#!/usr/bin/env python3\n"
    + '"""Minimal Cline NDJSON parser stub. Replace with the full\n'''
    "implementation from the cline-orchestration skill's scripts/\n"
    "directory, or call `harness-scaffold --update-parser` if such\n"
    "a flag exists in a future version.\"\"\"\n"
    + "from __future__ import annotations\n"
    + "import json, sys\n"
    + "from pathlib import Path\n"
    + "\n"
    + "def main(path):\n"
    + "    p = Path(path)\n"
    + "    if not p.exists() or p.stat().st_size == 0:\n"
    + '        print(json.dumps({"tokens": 0, "duration_ms": 0, "candidate_text": "",\n'
    + '                         "model": "", "provider": "", "finish_reason": "no_output",\n'
    + '                         "iterations": 0, "tool_calls": []}, indent=2))\n'
    + "        return\n"
    + "    tokens = duration_ms = 0\n"
    + '    candidate_text = model = provider = finish_reason = ""\n'
    + "    iterations = 0\n"
    + "    tool_calls = []\n"
    + "    with p.open() as f:\n"
    + "        for line in f:\n"
    + '            line = line.strip()\n'
    + "            if not line:\n"
    + "                continue\n"
    + "            try:\n"
    + "                obj = json.loads(line)\n"
    + "            except json.JSONDecodeError:\n"
    + "                continue\n"
    + '            if obj.get("type") == "run_result":\n'
    + '                agg = obj.get("aggregateUsage") or {}\n'
    + "                tokens = (\n"
    + "                    int(agg.get('inputTokens', 0) or 0)\n"
    + "                    + int(agg.get('outputTokens', 0) or 0)\n"
    + "                    + int(agg.get('cacheReadTokens', 0) or 0)\n"
    + "                )\n"
    + "                duration_ms = int(obj.get('durationMs', 0) or 0)\n"
    + "                candidate_text = obj.get('text', '') or ''\n"
    + "                finish_reason = obj.get('finishReason', '')\n"
    + "                iterations = int(obj.get('iterations', 0) or 0)\n"
    + '                m = obj.get("model") or {}\n'
    + '                model = m.get("id", ""); provider = m.get("provider", "")\n'
    + '    print(json.dumps({"tokens": tokens, "duration_ms": duration_ms,\n'
    + '                         "candidate_text": candidate_text,\n'
    + '                         "model": model, "provider": provider,\n'
    + '                         "finish_reason": finish_reason,\n'
    + '                         "iterations": iterations,\n'
    + '                         "tool_calls": tool_calls}, indent=2))\n'
    + "\n"
    + 'if __name__ == "__main__":\n'
    + "    main(sys.argv[1])\n"
)

COMPUTE_SUB_LOSSES_STUB = (
    GENERATED_HEADER
    + "#!/usr/bin/env python3\n"
    + '"""Per-cycle sub-loss scorer stub. Replace with the full\n'''
    "implementation from the cline-orchestration skill's references/\n"
    "directory, or implement your own 7 sub-losses using the\n"
    "WEIGHTS / GATES constants below as a starting point.\n"
    '"""\n'
    + "from __future__ import annotations\n"
    + "import json, sys\n"
    + "from pathlib import Path\n"
    + "\n"
    + "WEIGHTS = {\n"
    + '    "correctness": 1.0,\n'
    + '    "performance": 0.5,\n'
    + '    "safety": 1.0,\n'
    + '    "legibility": 0.3,\n'
    + '    "invariants": 1.0,\n'
    + '    "drift": 0.2,\n'
    + '    "cost": 0.3,\n'
    + "}\n"
    + 'GATES = {"correctness", "safety", "invariants"}\n'
    + "\n"
    + "def main(path):\n"
    + "    p = Path(path)\n"
    + "    if not p.exists():\n"
    + '        print(json.dumps({"error": f"cycle json not found: {path}"}))\n'
    + "        return\n"
    + "    raw = {}\n"
    + "    try:\n"
    + "        raw = json.loads(p.read_text())\n"
    + "    except json.JSONDecodeError:\n"
    + "        for line in p.read_text().splitlines():\n"
    + "            try:\n"
    + "                obj = json.loads(line.strip())\n"
    + '                if obj.get("type") == "run_result":\n'
    + '                    agg = obj.get("aggregateUsage") or {}\n'
    + "                    raw = {\n"
    + '                        "tokens": int(agg.get("inputTokens", 0) or 0) + int(agg.get("outputTokens", 0) or 0),\n'
    + '                        "elapsed_seconds": int(obj.get("durationMs", 0) or 0) // 1000,\n'
    + '                        "finish_reason": obj.get("finishReason", ""),\n'
    + '                        "exit_code": 0,\n'
    + '                        "candidate_text": obj.get("text", ""),\n'
    + '                        "model": (obj.get("model") or {}).get("id", ""),\n'
    + "                    }\n"
    + "                    break\n"
    + "            except json.JSONDecodeError:\n"
    + "                continue\n"
    + "    scores = {\n"
    + '        "correctness": 1.0 if raw.get("exit_code") == 0 and raw.get("candidate_text", "").strip() else 0.0,\n'
    + '        "performance": 1.0 if raw.get("elapsed_seconds", 999) <= 90 else 0.0,\n'
    + '        "safety": 1.0,\n'
    + '        "legibility": 1.0 if len(raw.get("candidate_text", "")) >= 10 else 0.3,\n'
    + '        "invariants": 1.0 if raw.get("exit_code") == 0 and raw.get("finish_reason") == "completed" else 0.0,\n'
    + '        "drift": 1.0,\n'
    + '        "cost": 1.0 if raw.get("tokens", 0) <= 4000 else 0.0,\n'
    + "    }\n"
    + '    out = {"sub_losses": {k: {"score": v, "details": {}} for k, v in scores.items()},\n'
    + '           "weights": WEIGHTS, "gates": list(GATES),\n'
    + '           "weighted_sum": sum(scores[k] * WEIGHTS[k] for k in scores),\n'
    + '           "weighted_total": sum(WEIGHTS.values()),\n'
    + '           "gates_passed": all(scores[g] >= 1.0 for g in GATES)}\n'
    + '    out["weighted_normalized"] = round(out["weighted_sum"] / out["weighted_total"], 4)\n'
    + "    print(json.dumps(out, indent=2))\n"
    + "\n"
    + 'if __name__ == "__main__":\n'
    + "    if len(sys.argv) < 2:\n"
    + '        print("usage: compute_sub_losses.py <cycle-N.json>", file=sys.stderr)\n'
    + "        sys.exit(2)\n"
    + "    main(sys.argv[1])\n"
)

CLINE_WRAPPER_SH = (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# cline-wrapper.sh — the ONLY way to invoke cline inside\n"
    + "# the loss loop.\n"
    + "#\n"
    + "# Usage:\n"
    + '#   verifiers/cline-wrapper.sh "<task-prompt>" --cwd PATH \\\n'
    + "#       --timeout 600 --cycle cycle-1 > cycle-1.json\n"
    + "#\n"
    + "# Why these flags:\n"
    + "# - --thinking none: many OpenAI-compat endpoints reject\n"
    + "#   the reasoning-token request shape. Change per provider.\n"
    + "# - --auto-approve true: required for non-interactive file\n"
    + "#   work. Safety is enforced by a separate transcript grep.\n"
    + "# - No --worktree: per-cycle directory already gives\n"
    + "#   isolation; --worktree triggers auth failures.\n"
    + "\n"
    + "set -euo pipefail\n"
    + "\n"
    + 'TASK=""; CWD=""; TIMEOUT=600; CYCLE="cycle-0"\n'
    + "while [[ $# -gt 0 ]]; do\n"
    + '  case "$1" in\n'
    + '    --cwd) CWD="$2"; shift 2 ;;\n'
    + '    --timeout) TIMEOUT="$2"; shift 2 ;;\n'
    + '    --cycle)\n'
    + '      if [[ "${2:-}" =~ ^[0-9]+$ ]]; then CYCLE="cycle-$2"; shift 2\n'
    + '      else CYCLE="${2:-cycle-0}"; shift 2; fi ;;\n'
    + '    --cycle=*) CYCLE="${1#--cycle=}"; shift ;;\n'
    + '    *) TASK="$1"; shift ;;\n'
    + "  esac\n"
    + "done\n"
    + '[[ -z "$TASK" || -z "$CWD" ]] && {\n'
    + '  echo \'{"error":"missing arg"}\' >&2; exit 2;\n'
    + "}\n"
    + "\n"
    + '# Resolve cline binary: $CLINE_BIN env, then PATH, then bail.\n'
    + 'CLINE_BIN="${CLINE_BIN:-$(command -v cline 2>/dev/null || true)}"\n'
    + '[[ -z "$CLINE_BIN" || ! -x "$CLINE_BIN" ]] && {\n'
    + '  echo \'{"error":"cline not found"}\' >&2; exit 3;\n'
    + "}\n"
    + "\n"
    + 'ITER_DIR="${CWD}/.iterations/${CYCLE}"\n'
    + 'mkdir -p "$ITER_DIR"\n'
    + "\n"
    + "# Seed the iter dir with the task's source files (so Cline\n"
    + "# has the actual problem to work on).\n"
    + "if command -v rsync >/dev/null 2>&1; then\n"
    + '  rsync -a --exclude=".iterations/" --exclude=".git/" \\\n'
    + '        --exclude="*.stderr" --exclude="cline.json" \\\n'
    + '        --exclude="cycle-summary.json" \\\n'
    + '        "$CWD"/ "$ITER_DIR"/ 2>/dev/null || true\n'
    + "else\n"
    + '  find "$CWD" -mindepth 1 -maxdepth 1 \\\n'
    + '       -not -name ".iterations" -not -name ".git" \\\n'
    + '       -exec cp -R {} "$ITER_DIR"/ \\; 2>/dev/null || true\n'
    + "fi\n"
    + "\n"
    + "START_TS=$(date +%s)\n"
    + 'RAW_OUT="${ITER_DIR}/cline.json"\n'
    + "EXIT_CODE=0\n"
    + "\n"
    + '"$CLINE_BIN" "$TASK" \\\n'
    + '  --cwd "$ITER_DIR" \\\n'
    + '  --auto-approve true \\\n'
    + '  --thinking none \\\n'
    + '  --json \\\n'
    + '  > "$RAW_OUT" 2>"${ITER_DIR}/cline.stderr" || EXIT_CODE=$?\n'
    + "\n"
    + "END_TS=$(date +%s)\n"
    + "ELAPSED=$((END_TS - START_TS))\n"
    + "\n"
    + 'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"\n'
    + 'PARSED=$(python3 "$SCRIPT_DIR/parse_cline_output.py" "$RAW_OUT")\n'
    + "\n"
    + "python3 -c '\n"
    + "import json, sys\n"
    + "out = json.loads(sys.argv[1])\n"
    + 'out.update({\n'
    + '    "cycle": sys.argv[2],\n'
    + '    "exit_code": int(sys.argv[3]),\n'
    + '    "elapsed_seconds": int(sys.argv[4]),\n'
    + '    "raw_output_path": sys.argv[5],\n'
    + "})\n"
    + 'print(json.dumps(out, indent=2))\n'
    + "' \"$PARSED\" \"$CYCLE\" \"$EXIT_CODE\" \"$ELAPSED\" \"$RAW_OUT\"\n"
)

RUN_DESIGN_SET_SH = lambda design_task_names: (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# verifiers/run-design-set.sh\n"
    + "# Run the wrapper + per-task grader for every design task\n"
    + "# and emit an aggregate JSON score.\n"
    + "\n"
    + "set -euo pipefail\n"
    + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
    + 'CYCLE="${CYCLE:-design-set-cycle-$(date +%s)}"\n'
    + 'RUNS_DIR="$PROJECT_DIR/logs/design-set-runs/$CYCLE"\n'
    + 'SCORE_FILE="$PROJECT_DIR/logs/design-set-score.json"\n'
    + 'mkdir -p "$RUNS_DIR"\n'
    + "\n"
    + "TASKS=(\n"
    + "".join('  "%s"\n' % t for t in design_task_names)
    + ")\n"
    + "\n"
    + "n_pass=0; n_total=0; total_tokens=0\n"
    + "results=()\n"
    + "\n"
    + "for task in \"${TASKS[@]}\"; do\n"
    + "  n_total=$((n_total + 1))\n"
    + '  task_dir="$PROJECT_DIR/test-tasks/design/$task"\n'
    + '  task_run_dir="$RUNS_DIR/$task"\n'
    + '  mkdir -p "$task_run_dir"\n'
    + "\n"
    + '  if [[ ! -d "$task_dir" ]]; then\n'
    + '    results+=("{\\"task\\":\\"$task\\",\\"status\\":\\"missing\\",\\"detail\\":\\"no task dir\\"}")\n'
    + "    continue\n"
    + "  fi\n"
    + "\n"
    + '  if [[ -f "$task_dir/prompt.txt" ]]; then\n'
    + '    prompt="$(cat "$task_dir/prompt.txt")"\n'
    + "  else\n"
    + '    prompt="Look at the files in this directory and complete the task described in the README."\n'
    + "  fi\n"
    + "\n"
    + '  iter_dir="$task_dir/.iterations/$CYCLE"\n'
    + '  mkdir -p "$iter_dir"\n'
    + '  task_cycle="cycle-$(date +%s)-$task"\n'
    + "\n"
    + '  echo "[run-design-set] running wrapper for $task ..." >&2\n'
    + '  if "$PROJECT_DIR/verifiers/cline-wrapper.sh" "$prompt" \\\n'
    + '       --cwd "$task_dir" --timeout 180 --cycle "$task_cycle" \\\n'
    + '       > "$task_run_dir/cycle-summary.json" 2>"$task_run_dir/wrapper.stderr"; then\n'
    + "    :\n"
    + "  else\n"
    + '    echo "[run-design-set] wrapper failed for $task (exit $?)" >&2\n'
    + "  fi\n"
    + "\n"
    + '  rm -rf "$task_run_dir/iter"\n'
    + '  if [[ -d "$task_dir/.iterations" ]]; then\n'
    + '    latest_iter="$(ls -1t "$task_dir/.iterations" | head -1)"\n'
    + '    if [[ -n "$latest_iter" ]]; then\n'
    + '      mv "$task_dir/.iterations/$latest_iter" "$task_run_dir/iter" 2>/dev/null || true\n'
    + "    fi\n"
    + "  fi\n"
    + "\n"
    + '  if [[ -x "$task_dir/grade.sh" ]]; then\n'
    + '    if "$task_dir/grade.sh" "$task_run_dir/iter" > "$task_run_dir/grade.txt" 2>&1; then\n'
    + '      n_pass=$((n_pass + 1)); grade_status="pass"\n'
    + "    else\n"
    + '      grade_status="fail"\n'
    + "    fi\n"
    + "  else\n"
    + '    grade_status="missing"\n'
    + "  fi\n"
    + "\n"
    + '  tok=0\n'
    + '  if [[ -s "$task_run_dir/cycle-summary.json" ]]; then\n'
    + '    tok=$(python3 -c "import json; print(int(json.load(open('"'"'"$task_run_dir/cycle-summary.json"'"'"' )).get('"'"'tokens'"'"',0) or 0))" 2>/dev/null || echo 0)\n'
    + "  fi\n"
    + '  total_tokens=$((total_tokens + tok))\n'
    + '  results+=("{\\"task\\":\\"$task\\",\\"status\\":\\"$grade_status\\",\\"tokens\\":$tok}")\n'
    + "done\n"
    + "\n"
    + 'pass_rate=$(python3 -c "print(round($n_pass / max($n_total, 1), 4))")\n'
    + "python3 -c \"\n"
    + "import json\n"
    + "score = {\n"
    + "    'cycle': '$CYCLE',\n"
    + "    'n_pass': $n_pass,\n"
    + "    'n_total': $n_total,\n"
    + "    'pass_rate': $pass_rate,\n"
    + "    'total_tokens': $total_tokens,\n"
    + "}\n"
    + 'print(json.dumps(score, indent=2))\n'
    + "\" > \"$SCORE_FILE\"\n"
    + 'cat "$SCORE_FILE"\n'
)

DESIGN_PROMPT_STUB = lambda task_desc: (
    GENERATED_HEADER
    + "\n"
    + "# " + task_desc + "\n"
    + "\n"
    + "(Write a 1-2 sentence description of the task here. The\n"
    + "agent reads this as the prompt.)\n"
)

DESIGN_README_STUB = lambda task_desc: (
    GENERATED_HEADER
    + "\n"
    + "# " + task_desc + "\n"
    + "\n"
    + "(Describe the task in detail: the input shape, the expected\n"
    + "output, and any edge cases. The grader uses this for\n"
    + "context.)\n"
)

DESIGN_GRADE_STUB = (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# TODO: write the deterministic grader for this task.\n"
    + "# Usage: grade.sh <iter-dir>\n"
    + "# Exits 0 on pass, 1 on fail.\n"
    + "set -euo pipefail\n"
    + 'ITER_DIR="${1:?usage: grade.sh <iter-dir>}"\n'
    + '[[ -d "$ITER_DIR" ]] || { echo "FAIL: not a dir" >&2; exit 1; }\n'
    + '[[ ! -d "$ITER_DIR/.iterations" ]] || { echo "FAIL: parent dir" >&2; exit 1; }\n'
    + 'echo "FAIL: grade.sh not implemented for this task yet" >&2\n'
    + "exit 1\n"
)

HELDOUT_README_STUB = lambda tid: (
    GENERATED_HEADER
    + "\n"
    + "# Held-out task " + tid + "\n"
    + "\n"
    + "This is a held-out task. The agent must NOT read this\n"
    + "directory. The grader at `verifiers/private/grader.sh`\n"
    + "runs the agent's candidate against this task.\n"
    + "\n"
    + "TODO: provide the actual task files here:\n"
    + "- the starting source file\n"
    + "- `prompt.txt` (the prompt given to the agent)\n"
    + "- `grade.sh` (the deterministic grader, chmod 700)\n"
    + "\n"
    + "The user (or a research skill) fills these in. The\n"
    + "agent's loop will only ever see the design tasks.\n"
)

PRIVATE_GRADER_STUB = (
    GENERATED_HEADER
    + "#!/usr/bin/env bash\n"
    + "# HELD-OUT GRADER. INTENTIONALLY hidden from the agent.\n"
    + "# The agent must NOT read this script, must NOT read any\n"
    + "# task under test-tasks/held-out/, and must NOT enumerate\n"
    + "# the contents of verifiers/private/.\n"
    + "\n"
    + "set -euo pipefail\n"
    + 'PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"\n'
    + 'CYCLE="${CYCLE:-held-out-$(date +%s)}"\n'
    + 'RUNS_DIR="$PROJECT_DIR/logs/held-out-runs/$CYCLE"\n'
    + 'SCORE_FILE="$PROJECT_DIR/logs/held-out-score.json"\n'
    + 'mkdir -p "$RUNS_DIR"\n'
    + "\n"
    + "# TODO: enumerate the 10 held-out tasks and for each: invoke\n"
    + "# the wrapper, run the per-task grader, aggregate pass_rate.\n"
    + "\n"
    + 'echo \'{"error": "held-out grader not implemented yet"}\' > "$SCORE_FILE"\n'
    + 'cat "$SCORE_FILE"\n'
)


# ----- scaffold functions -----

def scaffold_instruments(project):
    inst = project / "verifiers" / "instruments"
    inst.mkdir(parents=True, exist_ok=True)
    for name, content in INSTRUMENT_FILES.items():
        safe_write(inst / name, content, executable=True)


def scaffold_compute_sub_losses(project):
    safe_write(project / "verifiers" / "compute_sub_losses.py",
               COMPUTE_SUB_LOSSES_STUB)


def scaffold_parse_cline_output(project):
    safe_write(project / "verifiers" / "parse_cline_output.py",
               PARSE_CLINE_OUTPUT_STUB)


def scaffold_cline_wrapper(project, runtime):
    if runtime != "cline":
        content = (
            GENERATED_HEADER
            + "#!/usr/bin/env bash\n"
            + "# Wrapper for " + runtime + ".\n"
            + "# TODO: replace this stub with the appropriate\n"
            + "# invocation for your agent. See cline-orchestration\n"
            + "# skill for the pattern.\n"
            + "set -euo pipefail\n"
            + 'echo "TODO: implement ' + runtime + ' wrapper" >&2\n'
            + "exit 1\n"
        )
    else:
        content = CLINE_WRAPPER_SH
    safe_write(project / "verifiers" / "cline-wrapper.sh", content, executable=True)


def scaffold_run_design_set(project, design_task_names):
    safe_write(project / "verifiers" / "run-design-set.sh",
               RUN_DESIGN_SET_SH(design_task_names), executable=True)


def scaffold_design_task_stubs(project, tasks):
    design_dir = project / "test-tasks" / "design"
    design_dir.mkdir(parents=True, exist_ok=True)
    for i, task_desc in enumerate(tasks, 1):
        slug = word_truncate(slugify(task_desc) or f"task-{i:02d}", 40)
        task_dir = design_dir / ("%02d-%s" % (i, slug))
        task_dir.mkdir(parents=True, exist_ok=True)
        safe_write(task_dir / "prompt.txt", DESIGN_PROMPT_STUB(task_desc))
        safe_write(task_dir / "README.md", DESIGN_README_STUB(task_desc))
        safe_write(task_dir / "grade.sh", DESIGN_GRADE_STUB, executable=True)


def scaffold_held_out_placeholders(project, held_out):
    held_out_dir = project / "test-tasks" / "held-out"
    held_out_dir.mkdir(parents=True, exist_ok=True)
    for tid in held_out:
        task_dir = held_out_dir / tid
        task_dir.mkdir(parents=True, exist_ok=True)
        safe_write(task_dir / "README.md", HELDOUT_README_STUB(tid))


def scaffold_private_grader(project):
    private_dir = project / "verifiers" / "private"
    private_dir.mkdir(parents=True, exist_ok=True)
    grader = private_dir / "grader.sh"
    safe_write(grader, PRIVATE_GRADER_STUB, executable=True)
    chmod_700(private_dir)
    chmod_600(grader)


def scaffold_skill_dir(project):
    skills_dir = project / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, type=Path,
                        help="The directory to scaffold into")
    parser.add_argument("--goal-prompt", type=Path, default=None,
                        help="Path to the /goal prompt (default: <project>/GOAL.md)")
    parser.add_argument("--runtime", default=None,
                        choices=["cline", "codex", "aider"],
                        help="Agent runtime (default: detected from /goal prompt)")
    parser.add_argument("--no-private", action="store_true",
                        help="Skip the held-out grader scaffold")
    args = parser.parse_args()

    project = args.project_root.expanduser().resolve()
    project.mkdir(parents=True, exist_ok=True)

    goal_path = args.goal_prompt or (project / "GOAL.md")
    goal = goal_path.read_text() if goal_path.exists() else ""

    runtime = args.runtime or extract_runtime(goal) or "cline"
    design_tasks = extract_design_tasks(goal)
    design_names = []
    for i, t in enumerate(design_tasks, 1):
        slug = word_truncate(slugify(t) or f"task-{i:02d}", 40)
        design_names.append("%02d-%s" % (i, slug))
    held_out = extract_held_out_tasks(goal)

    print("scaffolding " + str(project), file=sys.stderr)
    print("  runtime:   " + runtime, file=sys.stderr)
    print("  design:    " + str(len(design_tasks)) + " tasks", file=sys.stderr)
    print("  held-out:  " + str(len(held_out)) + " tasks", file=sys.stderr)

    safe_write(project / "AGENTS.md", AGENTS_MD(project.name))
    safe_write(project / "README.md", README_MD(project.name, goal))
    if goal_path.exists() and goal_path != project / "GOAL.md":
        safe_write(project / "GOAL.md", goal)
    elif not (project / "GOAL.md").exists() and goal:
        safe_write(project / "GOAL.md", goal)
    scaffold_instruments(project)
    scaffold_compute_sub_losses(project)
    scaffold_parse_cline_output(project)
    scaffold_cline_wrapper(project, runtime)
    scaffold_run_design_set(project, design_names)
    scaffold_design_task_stubs(project, design_tasks)
    scaffold_held_out_placeholders(project, held_out)
    if not args.no_private:
        scaffold_private_grader(project)
    scaffold_skill_dir(project)

    (project / "logs").mkdir(exist_ok=True)
    print("done.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
