#!/usr/bin/env bash
# d6-method-drives-improvement grader
#
# Verifies the LFD *method* (not just the tools) works
# end-to-end. Runs the loop for 3 cycles with the
# fake-method wrapper (which simulates an agent's
# improvement across cycles) and asserts the loop's
# machinery for tracking improvement actually works:
#
#   - iteration log has 3 cycle entries
#   - best-cycle.json was updated (cycle 2 > cycle 1)
#   - per-cycle sub-losses.json files exist
#   - cycle 3's log line includes FORCED_ENTROPY=true
#     (no-improvement plateau triggers the rule)
#
# This is the "method" half of dogfood. The other 5
# design tasks (d1-d5) test the "tools" half (parsers,
# install, driver, scorer shape). Together they prove
# the LFD system is operationally correct AND that its
# core method (drive the agent to improvement) is wired
# up end-to-end.
set -uo pipefail

PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
REPO_ROOT="$(cd "$PROJECT_DIR/../.." && pwd)"
LOOP_DRIVER="$REPO_ROOT/skills/loop-driver/scripts/cycle.sh"
METHOD_WRAPPER="$PROJECT_DIR/verifiers/fake-method-wrapper.sh"

score=0.0

# ----- preconditions -----

if [[ ! -x "$LOOP_DRIVER" ]]; then
  echo "FAIL: cycle.sh not found at $LOOP_DRIVER" >&2
  echo "score=$score"; exit 1
fi
if [[ ! -x "$METHOD_WRAPPER" ]]; then
  echo "FAIL: fake-method-wrapper.sh not found at $METHOD_WRAPPER" >&2
  echo "score=$score"; exit 1
fi

# ----- set up state for the 3-cycle method run -----

LOG_FILE="$PROJECT_DIR/logs/iteration-log.md"
BEST_FILE="$PROJECT_DIR/logs/best-cycle.json"

# Reset the loop's tracking files so we start clean
mkdir -p "$PROJECT_DIR/logs"
date +%s > "$PROJECT_DIR/logs/.loop_start_ts"
echo "VERIFY: method test, $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$LOG_FILE"
echo '{"weighted_normalized": 0.0, "pass_rate": 0.0}' > "$BEST_FILE"

# Ensure the loop-driver symlink exists (run-verification.sh
# creates it but d6 can be invoked standalone)
if [[ ! -e "$PROJECT_DIR/loop-driver" ]]; then
  ln -s "$REPO_ROOT/skills/loop-driver" "$PROJECT_DIR/loop-driver"
fi

# Copy the sub-loss scorer (regenerated by the orchestrator;
# d6 needs it locally for the per-cycle sub-losses.json)
if [[ ! -f "$PROJECT_DIR/verifiers/compute_sub_losses.py" ]]; then
  cp "$REPO_ROOT/skills/cline-orchestration/references/compute-sub-losses.py" \
     "$PROJECT_DIR/verifiers/compute_sub_losses.py"
  D6_COPIED_SCORER=true
fi

# ----- run the loop for 3 cycles -----

for cycle in 1 2 3; do
  CYCLE_OUT=$("$LOOP_DRIVER" \
    --project-root "$PROJECT_DIR" \
    --cycle "$cycle" \
    --delta 0.0 \
    --max-stall 100 \
    --wrapper-timeout 30 \
    --runtime fake-method \
    --artifact-name lfd-system-driver \
    2>&1) || true
done

# ----- check 1: iteration log has 3 cycle entries -----

if ! grep -q "cycle 1:" "$LOG_FILE"; then
  echo "FAIL: iteration-log.md missing cycle 1 entry" >&2
  echo "score=$score"; exit 1
fi
if ! grep -q "cycle 2:" "$LOG_FILE"; then
  echo "FAIL: iteration-log.md missing cycle 2 entry" >&2
  echo "score=$score"; exit 1
fi
if ! grep -q "cycle 3:" "$LOG_FILE"; then
  echo "FAIL: iteration-log.md missing cycle 3 entry" >&2
  echo "score=$score"; exit 1
fi
echo "  check 1 PASS: iteration-log.md has 3 cycle entries"

# ----- check 2: best-cycle.json was updated (cycle 2 > cycle 1) -----

python3 - "$LOG_FILE" "$BEST_FILE" <<'PYEOF' && check2_ok=true || check2_ok=false
import json, sys
log_file, best_file = sys.argv[1], sys.argv[2]
# Parse cycle 1 and cycle 2 weighted_sum from the log
ws1 = ws2 = None
with open(log_file) as f:
    for line in f:
        if "cycle 1:" in line:
            import re
            m = re.search(r"weighted_sum=([\d.]+)", line)
            if m: ws1 = float(m.group(1))
        elif "cycle 2:" in line:
            import re
            m = re.search(r"weighted_sum=([\d.]+)", line)
            if m: ws2 = float(m.group(1))
if ws1 is None or ws2 is None:
    print(f"FAIL: could not parse weighted_sum from log: ws1={ws1} ws2={ws2}",
          file=sys.stderr)
    sys.exit(1)
if ws2 <= ws1:
    print(f"FAIL: cycle 2 weighted_sum {ws2} did not improve over cycle 1 {ws1}",
          file=sys.stderr)
    sys.exit(1)
PYEOF
if [[ $? -ne 0 ]]; then
  echo "score=$score"; exit 1
fi
echo "  check 2 PASS: best-cycle.json was updated (cycle 2 improved over cycle 1)"

# ----- check 3: per-cycle sub-losses.json files exist -----

n_sub_losses=0
for cycle in 1 2 3; do
  if [[ -f "$PROJECT_DIR/logs/cycle-$cycle/sub-losses.json" ]]; then
    n_sub_losses=$((n_sub_losses + 1))
  fi
done
if [[ $n_sub_losses -ne 3 ]]; then
  echo "FAIL: expected 3 sub-losses.json files, found $n_sub_losses" >&2
  echo "score=$score"; exit 1
fi
echo "  check 3 PASS: 3 per-cycle sub-losses.json files exist"

# ----- check 4: cycle 3's log line includes FORCED_ENTROPY=true -----

if ! grep "cycle 3:" "$LOG_FILE" | grep -q "FORCED_ENTROPY=true"; then
  echo "FAIL: cycle 3 log line missing FORCED_ENTROPY=true" >&2
  echo "  cycle 3 log line:" >&2
  grep "cycle 3:" "$LOG_FILE" >&2
  echo "score=$score"; exit 1
fi
echo "  check 4 PASS: cycle 3 log line includes FORCED_ENTROPY=true"

# ----- check 5: at least one cycle's weighted_sum >= 0.8 -----

# (cycle 2's improvement should push it well above 0.8)
max_ws=0
for cycle in 1 2 3; do
  ws=$(python3 -c "
import json, sys
try:
    d = json.load(open('$PROJECT_DIR/logs/cycle-$cycle/sub-losses.json'))
    print(d.get('weighted_normalized', 0.0))
except: print(0)
")
  max_ws=$(python3 -c "print(max($max_ws, $ws))")
done
if python3 -c "import sys; sys.exit(0 if $max_ws >= 0.8 else 1)"; then
  echo "  check 5 PASS: max weighted_sum $max_ws >= 0.8"
else
  echo "FAIL: no cycle reached weighted_sum >= 0.8 (max was $max_ws)" >&2
  echo "score=$score"; exit 1
fi

# ----- all checks passed -----

# Clean up the 3 cycles we ran
rm -rf "$PROJECT_DIR/logs/cycle-1" "$PROJECT_DIR/logs/cycle-2" "$PROJECT_DIR/logs/cycle-3"

# Reset the iteration log and best-cycle
echo "VERIFY: method test reset, $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$LOG_FILE"
echo '{"weighted_normalized": 0.0, "pass_rate": 0.0}' > "$BEST_FILE"

# Remove the copied scorer if d6 created it
if [[ "${D6_COPIED_SCORER:-false}" == "true" ]]; then
  rm -f "$PROJECT_DIR/verifiers/compute_sub_losses.py"
fi

score=1.0
echo "score=$score"
exit 0
