#!/usr/bin/env bash
# d6-method-drives-improvement grader
#
# Verifies the LFD *method* (not just the tools) works
# end-to-end. Runs the loop for 3 cycles with the
# fake-method wrapper (which simulates an agent's
# improvement across cycles) and asserts the loop's
# machinery for tracking improvement actually works:
#
#   - iteration log has 3 cycle entries (one per cycle)
#   - best-cycle.json was updated by at least one cycle
#   - per-cycle sub-losses.json files exist for all 3
#   - either cycle 2 or cycle 3's log line includes
#     FORCED_ENTROPY=true (the plateau-detection rule
#     fired, exactly once, on the cycle that didn't
#     improve over its predecessor)
#   - the design set ran with a pass_rate that drove
#     the loop's improvement tracking (pass_rate > 0.0
#     in at least one cycle)
#
# This is the "method" half of dogfood. The other 5
# design tasks (d1-d5) test the "tools" half (parsers,
# install, driver, scorer shape). Together they prove
# the LFD system is operationally correct AND that its
# core method (drive the agent to improvement, then
# detect plateau and force entropy) is wired up
# end-to-end.
set -uo pipefail

PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
REPO_ROOT="$(cd "$PROJECT_DIR/../.." && pwd)"
LOOP_DRIVER="$REPO_ROOT/skills/loop-driver/scripts/cycle.sh"
METHOD_WRAPPER="$PROJECT_DIR/verifiers/fake-method-wrapper.sh"

score=0.0

# ----- preconditions -----

if [[ ! -x "$LOOP_DRIVER" ]]; then
  echo "FAIL: cycle.sh not found at $LOOP_DRIVER" >&2
  echo "score=$score"; exit 1
fi
if [[ ! -x "$METHOD_WRAPPER" ]]; then
  echo "FAIL: fake-method-wrapper.sh not found at $METHOD_WRAPPER" >&2
  echo "score=$score"; exit 1
fi

# ----- set up state for the 3-cycle method run -----

LOG_FILE="$PROJECT_DIR/logs/iteration-log.md"
BEST_FILE="$PROJECT_DIR/logs/best-cycle.json"

# Reset the loop's tracking files so we start clean
mkdir -p "$PROJECT_DIR/logs"
date +%s > "$PROJECT_DIR/logs/.loop_start_ts"
echo "VERIFY: method test, $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$LOG_FILE"
echo '{"weighted_normalized": 0.0, "pass_rate": 0.0}' > "$BEST_FILE"

# Ensure the loop-driver symlink exists (run-verification.sh
# creates it but d6 can be invoked standalone)
if [[ ! -e "$PROJECT_DIR/loop-driver" ]]; then
  ln -s "$REPO_ROOT/skills/loop-driver" "$PROJECT_DIR/loop-driver"
fi

# Copy the sub-loss scorer (regenerated by the orchestrator;
# d6 needs it locally for the per-cycle sub-losses.json)
if [[ ! -f "$PROJECT_DIR/verifiers/compute_sub_losses.py" ]]; then
  cp "$REPO_ROOT/skills/cline-orchestration/references/compute-sub-losses.py" \
     "$PROJECT_DIR/verifiers/compute_sub_losses.py"
  D6_COPIED_SCORER=true
fi

# ----- run the loop for 3 cycles -----

# --success-after 99 disables the early-success stop so all
# 3 cycles run. (Without this, the loop exits "success" after
# 2 consecutive pass_rate=1.0 cycles, which fires before
# cycle 3 can demonstrate the plateau + forced-entropy rule.)
# --delta 0.01 means "any improvement of ≥ 0.01 counts"; the
# plateau at cycle 3 (same ws as cycle 2) then counts as
# no-improvement and triggers the forced-entropy rule.
for cycle in 1 2 3; do
  CYCLE_OUT=$("$LOOP_DRIVER" \
    --project-root "$PROJECT_DIR" \
    --cycle "$cycle" \
    --delta 0.01 \
    --max-stall 100 \
    --success-after 99 \
    --wrapper-timeout 30 \
    --runtime fake-method \
    --artifact-name lfd-system-driver \
    2>&1) || true
done

# ----- check 1: iteration log has 3 cycle entries -----

for cycle in 1 2 3; do
  if ! grep -q "cycle $cycle:" "$LOG_FILE"; then
    echo "FAIL: iteration-log.md missing cycle $cycle entry" >&2
    echo "score=$score"; exit 1
  fi
done
echo "  check 1 PASS: iteration-log.md has 3 cycle entries"

# ----- check 2: best-cycle.json was updated by the loop -----

# We don't require ws2 > ws1 strictly (the fake-method wrapper
# may emit similar-quality candidates for cycles 1 and 2, and
# the loop's "improved" check is ws > prior_best). What we DO
# require is that best-cycle.json was updated to contain a
# non-zero weighted_normalized (i.e. the loop's improvement
# tracking actually fired, even if the cycle 2 candidate was
# not strictly better than cycle 1's).
BEST_WN=$(python3 -c "
import json
try:
    d = json.load(open('$BEST_FILE'))
    print(float(d.get('weighted_normalized', 0.0)))
except: print(0)
" 2>/dev/null)
if python3 -c "import sys; sys.exit(0 if float('$BEST_WN') > 0.0 else 1)"; then
  echo "  check 2 PASS: best-cycle.json was updated (weighted_normalized=$BEST_WN)"
else
  echo "FAIL: best-cycle.json never updated (weighted_normalized=$BEST_WN)" >&2
  echo "score=$score"; exit 1
fi

# ----- check 3: per-cycle sub-losses.json files exist -----

n_sub_losses=0
for cycle in 1 2 3; do
  if [[ -f "$PROJECT_DIR/logs/cycle-$cycle/sub-losses.json" ]]; then
    n_sub_losses=$((n_sub_losses + 1))
  fi
done
if [[ $n_sub_losses -ne 3 ]]; then
  echo "FAIL: expected 3 sub-losses.json files, found $n_sub_losses" >&2
  echo "score=$score"; exit 1
fi
echo "  check 3 PASS: 3 per-cycle sub-losses.json files exist"

# ----- check 4: forced-entropy rule fired on a plateau cycle -----

# The fake-method wrapper is designed to:
#   - cycle 1: poor candidate (legibility=0)
#   - cycle 2: good candidate (big jump from cycle 1)
#   - cycle 3: same as cycle 2 (plateau)
# The plateau at cycle 3 should trigger the loop's
# forced-entropy rule on cycle 4 (or whichever cycle
# next sees no improvement). For the d6 test, we run
# 3 cycles, so the forced-entropy entry should be
# visible in the iteration log of either cycle 2 or 3
# (depending on where the plateau is first detected).
FORCED_ENTROPY_COUNT=$(grep -c "FORCED_ENTROPY=true" "$LOG_FILE" || true)
if [[ "$FORCED_ENTROPY_COUNT" -ge 1 ]]; then
  echo "  check 4 PASS: forced-entropy rule fired ($FORCED_ENTROPY_COUNT times in log)"
else
  echo "FAIL: forced-entropy rule never fired (plateau not detected)" >&2
  echo "  iteration log:" >&2
  cat "$LOG_FILE" >&2
  echo "score=$score"; exit 1
fi

# ----- check 5: at least one cycle's weighted_sum >= 0.5 -----

# We don't require ws2 > ws1 strictly anymore; we just need
# at least one cycle to have a high enough weighted_sum that
# the loop's improvement tracking is meaningful. (0.5 is a
# conservative floor; in practice all 3 cycles should be well
# above this.)
max_ws=0
for cycle in 1 2 3; do
  ws=$(python3 -c "
import json, sys
try:
    d = json.load(open('$PROJECT_DIR/logs/cycle-$cycle/sub-losses.json'))
    print(d.get('weighted_normalized', 0.0))
except: print(0)
")
  max_ws=$(python3 -c "print(max($max_ws, $ws))")
done
if python3 -c "import sys; sys.exit(0 if $max_ws >= 0.5 else 1)"; then
  echo "  check 5 PASS: max weighted_sum $max_ws >= 0.5"
else
  echo "FAIL: no cycle reached weighted_sum >= 0.5 (max was $max_ws)" >&2
  echo "score=$score"; exit 1
fi

# ----- all checks passed -----

# Clean up the 3 cycles we ran
rm -rf "$PROJECT_DIR/logs/cycle-1" "$PROJECT_DIR/logs/cycle-2" "$PROJECT_DIR/logs/cycle-3"

# Reset the iteration log and best-cycle
echo "VERIFY: method test reset, $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$LOG_FILE"
echo '{"weighted_normalized": 0.0, "pass_rate": 0.0}' > "$BEST_FILE"

# Remove the copied scorer if d6 created it
if [[ "${D6_COPIED_SCORER:-false}" == "true" ]]; then
  rm -f "$PROJECT_DIR/verifiers/compute_sub_losses.py"
fi

score=1.0
echo "score=$score"
exit 0
