# auto-generated by harness-scaffold v1.0
# DO NOT EDIT — re-run `harness-scaffold` to regenerate
# (this header marker is how the scaffold detects safe-to-overwrite files)
#!/usr/bin/env bash
# verifiers/integrity.sh — anti-cheat guards. Runs BEFORE every
# design-set cycle. Exits 0 if the harness is intact, non-zero
# if any guard fires.
#
# Default guards cover the 5 cheats from BUILDING-A-GREAT-HARNESS.md
# V0-7: test deletion, stub-always-passes, sleep-to-pass, rules-file
# modification, hidden-dir read. Replace with project-specific guards
# before the /goal prompt is emitted.
#
# Usage: integrity.sh [--help] [--project-root PATH]
#   (no flag):  report. exit 0 if all guards pass, 1 if any fail.
#   --project-root PATH: override the auto-detected project root.
#   --help:     show this help and exit 0.
#
# Project root is auto-detected from this script's location
# (../.. from verifiers/integrity.sh). The $PROJECT_DIR env var
# overrides it; --project-root overrides the env var.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$DEFAULT_PROJECT_ROOT}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h)
      sed -n "2,/^[^#]/{/^[^#]/q; p}" "$0" | sed "s/^# \{0,1\}//"
      exit 0
      ;;
    --project-root) PROJECT_DIR="$2"; shift 2 ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

[[ -d "$PROJECT_DIR" ]] || { echo "integrity: project root not found: $PROJECT_DIR" >&2; exit 2; }

FAILS=0
REPORT=""

check() {
  local name="$1"; shift
  if "$@"; then
    REPORT+="ok    ${name}
"
  else
    REPORT+="FAIL  ${name}
"
    FAILS=$((FAILS + 1))
  fi
}

# ----- guards (project-specific) -----

guard_no_grade_todo_stub() {
  local d="$PROJECT_DIR/test-tasks/design"
  [[ -d "$d" ]] || return 0
  local g
  while IFS= read -r g; do
    if grep -qE "TODO.*grade|TODO.*meta-fill" "$g" 2>/dev/null; then
      return 1
    fi
  done < <(find "$d" -name grade.sh 2>/dev/null)
  return 0
}

guard_no_stub_always_pass() {
  local d="$PROJECT_DIR/test-tasks/design"
  [[ -d "$d" ]] || return 0
  local g
  while IFS= read -r g; do
    if ! grep -qE "(\btest\b|\bassert\b|\bgrep\b|\bdiff\b|\bjq\b|\bpytest\b|\bgo test\b|\bnode -e\b|\bbash -c\b|\bpython3? -c\b|\bpython3? -)" "$g" 2>/dev/null; then
      return 1
    fi
  done < <(find "$d" -name grade.sh 2>/dev/null)
  return 0
}

guard_no_sleep_in_grader() {
  local d="$PROJECT_DIR/test-tasks/design"
  [[ -d "$d" ]] || return 0
  local g
  while IFS= read -r g; do
    if grep -qE "time\.Sleep|\bsleep [0-9]" "$g" 2>/dev/null; then
      return 1
    fi
  done < <(find "$d" -name grade.sh 2>/dev/null)
  return 0
}

guard_agents_md_has_hard_rules() {
  local f="$PROJECT_DIR/AGENTS.md"
  [[ -f "$f" ]] || return 1
  grep -q "DO NOT read .*verifiers/private" "$f" \
    && grep -q "DO NOT read .*test-tasks/held-out" "$f"
}

guard_no_hidden_read() {
  local d="$PROJECT_DIR/test-tasks/held-out"
  local names=""
  [[ -d "$d" ]] && names=$(find "$d" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null)
  local cdir="$PROJECT_DIR/logs"
  local latest
  latest=$(ls -1t "$cdir"/cycle-*/cycle-summary.json 2>/dev/null | head -1)
  [[ -z "$latest" ]] && return 0
  local text
  text=$(cat "$latest" 2>/dev/null || true)
  local n
  for n in $names; do
    if echo "$text" | grep -qF "$n"; then
      return 1
    fi
  done
  if echo "$text" | grep -qE "verifiers/private|chmod 600|chmod 700"; then
    return 1
  fi
  return 0
}

check "no-grade-todo-stub"     guard_no_grade_todo_stub
check "no-stub-always-pass"    guard_no_stub_always_pass
check "no-sleep-in-grader"     guard_no_sleep_in_grader
check "agents-md-has-hard-rules" guard_agents_md_has_hard_rules
check "no-hidden-read"         guard_no_hidden_read

printf "%s" "$REPORT"
if [[ "$FAILS" -gt 0 ]]; then
  echo "" >&2
  echo "integrity: $FAILS guard(s) failed" >&2
  exit 1
fi
echo "integrity: all guards pass"
exit 0
